[package]
name = "awidat-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Awidat CLI binary."

[[bin]]
name = "awidat"
path = "src/main.rs"

[dependencies]
awidat-proto = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
