//! ASS / libass caption burn-in.
//!
//! When a [`TitlePlan`] carries per-word timings (WhisperX output),
//! the renderer prefers libass over `drawtext`. libass gives us
//! real glyph fallback, real bold/italic, karaoke `\k` reveal
//! timing, outline + shadow, and kerning — none of which
//! drawtext supports.
//!
//! This module owns the ASS file format generation; it knows
//! nothing about ffmpeg argv assembly. The timeline planner calls
//! [`is_libass_eligible`] to gate the path and [`render_ass_file`]
//! to materialize the subtitle file on disk.
//!
//! Coexistence: drawtext stays the default for plain titles,
//! reveal modes, rich text, and anything without WhisperX-style
//! word timings. Only role=="caption" + non-empty word_timings
//! switches the renderer to libass — that's the slice where
//! karaoke unlocks real value.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::timeline::{TitlePlan, TitlePosition, TitleWeight};

/// 1080p reference frame that title font sizes are authored against.
/// Mirrors `TIMELINE_RENDER_WIDTH` / `TIMELINE_RENDER_HEIGHT` in
/// `timeline.rs` so libass renders at the same scale as drawtext.
pub(crate) const ASS_REFERENCE_WIDTH: u32 = 1920;
pub(crate) const ASS_REFERENCE_HEIGHT: u32 = 1080;

/// Auto-detect: a [`TitlePlan`] is rendered via libass when
/// (a) it has at least one transcript word timing, and
/// (b) its role is "caption" (or anything caption-shaped — we
/// don't ASS-render plain `title` overlays since they have no
/// karaoke timing to gain from libass).
///
/// All other titles continue to fall through to drawtext.
pub(crate) fn is_libass_eligible(title: &TitlePlan) -> bool {
    if title.word_timings.is_empty() {
        return false;
    }
    matches!(title.role.as_str(), "caption" | "captions" | "subtitle" | "subtitles")
}

/// Render `title` to a `.ass` file inside `workdir`. Returns the
/// absolute path written. The file name includes the title start
/// time so concurrent captions don't clobber each other.
pub(crate) fn render_ass_file(
    title: &TitlePlan,
    workdir: &Path,
    sequence: usize,
) -> io::Result<PathBuf> {
    fs::create_dir_all(workdir)?;
    let path = workdir.join(format!(
        "caption-{:04}-{:.3}s.ass",
        sequence,
        title.start_s.max(0.0)
    ));
    let body = build_ass_document(title);
    fs::write(&path, body)?;
    Ok(path)
}

/// Build the ASS subtitle document for a captioned title.
///
/// Layout:
/// - One global `[Script Info]` header at 1920x1080.
/// - One `[V4+ Styles]` row matching the title's font/weight/color.
/// - One `Dialogue:` line per captioned step. Each Dialogue line
///   carries karaoke `\k<centiseconds>` tags so libass reveals
///   words in sync with their transcript timestamps — same
///   semantics as the cumulative-prefix drawtext fallback, but
///   without re-drawing the whole frame every word.
pub(crate) fn build_ass_document(title: &TitlePlan) -> String {
    let mut out = String::new();
    push_script_info(&mut out);
    push_styles(&mut out, title);
    push_events(&mut out, title);
    out
}

fn push_script_info(out: &mut String) {
    out.push_str("[Script Info]\n");
    out.push_str("; Generated by awidat-render libass caption path\n");
    out.push_str("ScriptType: v4.00+\n");
    out.push_str(&format!("PlayResX: {ASS_REFERENCE_WIDTH}\n"));
    out.push_str(&format!("PlayResY: {ASS_REFERENCE_HEIGHT}\n"));
    out.push_str("WrapStyle: 0\n");
    out.push_str("ScaledBorderAndShadow: yes\n");
    out.push('\n');
}

fn push_styles(out: &mut String, title: &TitlePlan) {
    out.push_str("[V4+ Styles]\n");
    out.push_str(
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, \
         BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, \
         BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n",
    );
    let bold_flag = if matches!(title.font_weight, TitleWeight::Bold) {
        -1
    } else {
        0
    };
    let primary = hex_to_ass_color(&title.color);
    // Karaoke fill secondary colour: the "unread" word state.
    // libass paints PrimaryColour on already-spoken words and
    // SecondaryColour on the upcoming ones.
    let secondary = "&H00FFFFFF";
    let outline = "&H00000000";
    let back = "&H80000000";
    // Vertical alignment: bottom = 2, center = 5, top = 8. These
    // numbers are libass numpad-style.
    let alignment = match title.position {
        TitlePosition::Top => 8,
        TitlePosition::Center => 5,
        TitlePosition::Bottom => 2,
    };
    let margin_v = match title.position {
        TitlePosition::Top => 54,    // ~5% of 1080
        TitlePosition::Center => 0,
        TitlePosition::Bottom => 162, // ~15% of 1080 (above the safe edge)
    };
    out.push_str(&format!(
        "Style: Caption,{font},{size},{primary},{secondary},{outline},{back},\
         {bold},0,0,0,100,100,0,0,1,3,2,{alignment},80,80,{margin_v},1\n",
        font = ass_default_fontname(),
        size = title.font_size,
        primary = primary,
        secondary = secondary,
        outline = outline,
        back = back,
        bold = bold_flag,
        alignment = alignment,
        margin_v = margin_v,
    ));
    out.push('\n');
}

fn push_events(out: &mut String, title: &TitlePlan) {
    out.push_str("[Events]\n");
    out.push_str(
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n",
    );
    let dialogues = build_dialogue_lines(title);
    for dialogue in dialogues {
        out.push_str(&dialogue);
        out.push('\n');
    }
}

/// Synthesize one Dialogue line per "step" (cumulative word
/// prefix). Each line spans the full title window so the karaoke
/// `\k` durations inside paint reveal in sync with the transcript.
///
/// Why one line and not one-per-word: libass `\k` tags chain
/// within a single Dialogue, painting words in PrimaryColour as
/// their `\k` duration elapses. That's the karaoke reveal we want.
fn build_dialogue_lines(title: &TitlePlan) -> Vec<String> {
    let words: Vec<&crate::timeline::CaptionWordTiming> = title
        .word_timings
        .iter()
        .filter(|w| {
            !w.text.trim().is_empty()
                && w.start_s.is_finite()
                && w.end_s.is_finite()
                && w.end_s >= w.start_s
        })
        .collect();
    if words.is_empty() {
        return Vec::new();
    }
    let start = format_ass_time(title.start_s.max(0.0));
    let end = format_ass_time(title.end_s.max(title.start_s));

    // Build the karaoke run for one Dialogue line. Lead-in (any gap
    // between title.start_s and the first word) is encoded as a
    // leading `\k` on an empty group so libass holds the line idle.
    let mut text = String::new();
    let first_word_start = words.first().map(|w| w.start_s).unwrap_or(title.start_s);
    let lead_in_cs = seconds_to_centiseconds((first_word_start - title.start_s).max(0.0));
    if lead_in_cs > 0 {
        text.push_str(&format!("{{\\k{lead_in_cs}}}"));
    }
    for (idx, word) in words.iter().enumerate() {
        let dur_cs = seconds_to_centiseconds((word.end_s - word.start_s).max(0.0));
        let glyphs = escape_ass_text(word.text.trim());
        if idx > 0 {
            text.push(' ');
        }
        text.push_str(&format!("{{\\k{dur_cs}}}{glyphs}"));
    }

    vec![format!(
        "Dialogue: 0,{start},{end},Caption,,0,0,0,,{text}",
    )]
}

/// ASS uses `H:MM:SS.cc` (centiseconds). Source seconds are master
/// timeline floats. Clamp to >= 0 and to 9:59:59.99 to avoid
/// pathological negative values upstream from breaking the format.
pub(crate) fn format_ass_time(seconds: f64) -> String {
    let mut total_cs = (seconds.max(0.0) * 100.0).round() as i64;
    let max_cs: i64 = 9 * 360_000 + 59 * 6_000 + 59 * 100 + 99;
    if total_cs > max_cs {
        total_cs = max_cs;
    }
    let cs = total_cs % 100;
    let total_s = total_cs / 100;
    let s = total_s % 60;
    let total_m = total_s / 60;
    let m = total_m % 60;
    let h = total_m / 60;
    format!("{h}:{m:02}:{s:02}.{cs:02}")
}

fn seconds_to_centiseconds(seconds: f64) -> u32 {
    if !seconds.is_finite() || seconds <= 0.0 {
        return 0;
    }
    (seconds * 100.0).round().max(0.0) as u32
}

/// Convert `#RRGGBB` (or `#RRGGBBAA`) into ASS `&HAABBGGRR` form.
/// libass uses 0xAABBGGRR with alpha as "transparency" (0x00 =
/// opaque, 0xFF = fully transparent), the inverse of what most
/// graphics layers ship. Fall back to opaque white on parse error
/// so the caption is still visible.
pub(crate) fn hex_to_ass_color(hex: &str) -> String {
    let trimmed = hex.trim().trim_start_matches('#');
    let parse = |start: usize| u8::from_str_radix(trimmed.get(start..start + 2)?, 16).ok();
    let (r, g, b, a) = match trimmed.len() {
        6 => (parse(0), parse(2), parse(4), Some(0x00)),
        8 => (parse(0), parse(2), parse(4), parse(6).map(|alpha| 0xFF - alpha)),
        _ => (None, None, None, None),
    };
    match (r, g, b, a) {
        (Some(r), Some(g), Some(b), Some(a)) => {
            format!("&H{a:02X}{b:02X}{g:02X}{r:02X}")
        }
        _ => "&H00FFFFFF".to_string(),
    }
}

/// libass parses `{...}` as override blocks, `\` as escape, and
/// newlines as soft breaks. Escape the bare characters; we'd
/// rather caption text render as literal punctuation than as
/// drawtext-style filter syntax.
fn escape_ass_text(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '{' => out.push_str("\\{"),
            '}' => out.push_str("\\}"),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\N"),
            _ => out.push(ch),
        }
    }
    out
}

/// libass falls back to system fonts when this name isn't bundled.
/// We don't ship a font yet, so we name the same generic family
/// the drawtext path probes — keeps captions visually similar
/// between the two code paths when both are in flight (e.g.,
/// drawtext for short titles, libass for word-timed captions).
fn ass_default_fontname() -> &'static str {
    "Arial"
}

/// ffmpeg's `subtitles=` filter parses its argument as a key/value
/// list. Single quotes wrap the path so spaces and `=` inside are
/// safe, and embedded single quotes are escaped as `\\\'` per
/// ffmpeg filter quoting rules.
pub(crate) fn ffmpeg_subtitles_filter_arg(path: &Path) -> String {
    let display = path.to_string_lossy();
    let escaped = display.replace('\\', "\\\\").replace('\'', "\\\\\\'");
    format!("subtitles='{escaped}'")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::timeline::{
        CaptionWordTiming, TextReveal, TitleAnimation, TitlePlan, TitlePosition, TitleWeight,
    };

    fn caption_with_words() -> TitlePlan {
        TitlePlan {
            text: "hello world".into(),
            start_s: 1.0,
            end_s: 2.5,
            position: TitlePosition::Bottom,
            font_size: 64,
            color: "#FFFFFF".into(),
            font_weight: TitleWeight::Bold,
            animation: TitleAnimation::None,
            reveal: TextReveal::None,
            role: "caption".into(),
            safe_area: None,
            rich_segments: Vec::new(),
            word_timings: vec![
                CaptionWordTiming {
                    text: "hello".into(),
                    start_s: 1.0,
                    end_s: 1.6,
                },
                CaptionWordTiming {
                    text: "world".into(),
                    start_s: 1.6,
                    end_s: 2.4,
                },
            ],
            animations: Vec::new(),
        }
    }

    #[test]
    fn eligibility_requires_caption_role_and_word_timings() {
        let mut title = caption_with_words();
        assert!(is_libass_eligible(&title));
        title.role = "title".into();
        assert!(!is_libass_eligible(&title));
        title.role = "caption".into();
        title.word_timings.clear();
        assert!(!is_libass_eligible(&title));
    }

    #[test]
    fn ass_document_contains_karaoke_tags_and_word_text() {
        let title = caption_with_words();
        let doc = build_ass_document(&title);
        assert!(doc.contains("[Script Info]"));
        assert!(doc.contains("[V4+ Styles]"));
        assert!(doc.contains("[Events]"));
        assert!(doc.contains("\\k"), "missing karaoke tag in: {doc}");
        assert!(doc.contains("hello"));
        assert!(doc.contains("world"));
        // Karaoke durations should be word durations in centiseconds
        // (1.6 - 1.0 = 60cs ; 2.4 - 1.6 = 80cs).
        assert!(doc.contains("\\k60"), "expected hello duration 60cs in: {doc}");
        assert!(doc.contains("\\k80"), "expected world duration 80cs in: {doc}");
    }

    #[test]
    fn hex_to_ass_color_uses_bgr_with_alpha() {
        // #FF0000 (red) → &H000000FF (alpha 00 = opaque, BGR=0000FF).
        assert_eq!(hex_to_ass_color("#FF0000"), "&H000000FF");
        // White stays white in any channel order.
        assert_eq!(hex_to_ass_color("#FFFFFF"), "&H00FFFFFF");
        // Bad input falls back to opaque white.
        assert_eq!(hex_to_ass_color("not-a-color"), "&H00FFFFFF");
    }

    #[test]
    fn format_ass_time_uses_centiseconds() {
        assert_eq!(format_ass_time(0.0), "0:00:00.00");
        assert_eq!(format_ass_time(1.235), "0:00:01.24");
        assert_eq!(format_ass_time(3661.5), "1:01:01.50");
    }

    #[test]
    fn escape_ass_text_neutralizes_override_braces() {
        assert_eq!(escape_ass_text("hi {there}"), "hi \\{there\\}");
        assert_eq!(escape_ass_text("a\\b"), "a\\\\b");
    }

    #[test]
    fn render_ass_file_writes_to_workdir() {
        let dir = tempfile::tempdir().unwrap();
        let title = caption_with_words();
        let path = render_ass_file(&title, dir.path(), 0).unwrap();
        assert!(path.exists());
        assert!(path.extension().and_then(|e| e.to_str()) == Some("ass"));
        let body = fs::read_to_string(&path).unwrap();
        assert!(body.contains("\\k"));
    }
}
