//! ASS / libass caption burn-in.
//!
//! When a [`TitlePlan`] carries per-word timings (WhisperX output),
//! the renderer prefers libass over `drawtext`. libass gives us
//! real glyph fallback, real bold/italic, karaoke `\k` reveal
//! timing, outline + shadow, and kerning — none of which
//! drawtext supports.
//!
//! This module owns the ASS file format generation; it knows
//! nothing about ffmpeg argv assembly. The timeline planner calls
//! [`is_libass_eligible`] to gate the path and [`render_ass_file`]
//! to materialize the subtitle file on disk.
//!
//! Coexistence: drawtext stays the default for plain titles,
//! reveal modes, and rich text. All caption-role overlays
//! (role == "caption" | "subtitle") use libass — both
//! word-timed (karaoke `\k` tags) and whole-cue (plain Dialogue).

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use awidat_proto::subtitle::SubtitleTrack;

use crate::timeline::{
    CaptionRenderBackground, CaptionRenderCasing, CaptionRenderWeight, RenderCanvas, TitlePlan,
    TitlePosition, TitleWeight,
};


#[derive(Debug, Clone, Copy)]
struct CaptionLayoutProfile {
    margin_l: u32,
    margin_r: u32,
    margin_v_bottom: u32,
    margin_v_top: u32,
    max_chars_per_line: usize,
}

impl CaptionLayoutProfile {
    fn for_title(title: &TitlePlan) -> Self {
        match title.safe_area.as_deref() {
            Some("mobile" | "9:16" | "vertical") => Self {
                margin_l: 160,
                margin_r: 160,
                margin_v_bottom: 216,
                margin_v_top: 80,
                max_chars_per_line: 18,
            },
            Some("lower_third") => Self {
                margin_l: 80,
                margin_r: 80,
                margin_v_bottom: 300, // ~28% of the 1080 reference: clears a typical lower-third banner
                margin_v_top: 54,
                max_chars_per_line: 32,
            },
            _ => Self {
                margin_l: 80,
                margin_r: 80,
                margin_v_bottom: 162,
                margin_v_top: 54,
                max_chars_per_line: 32,
            },
        }
    }
}

/// A [`TitlePlan`] is rendered via libass when its role is
/// "caption" (or any caption-shaped alias: "captions", "subtitle",
/// "subtitles"). That covers both whole-cue and word-timed karaoke
/// captions — the industry-standard subtitle engine handles both.
/// Plain `title` overlays keep the `drawtext` path.
///
/// All other roles continue to fall through to drawtext.
pub(crate) fn is_libass_eligible(title: &TitlePlan) -> bool {
    // Captions/subtitles always render via libass — the industry-standard
    // subtitle engine — whether word-timed (karaoke) or whole-cue. Plain
    // `title` overlays keep the drawtext path.
    matches!(
        title.role.as_str(),
        "caption" | "captions" | "subtitle" | "subtitles"
    )
}

/// Render `title` to a `.ass` file inside `workdir`. Returns the
/// absolute path written. The file name includes the title start
/// time so concurrent captions don't clobber each other.
pub(crate) fn render_ass_file(
    title: &TitlePlan,
    workdir: &Path,
    sequence: usize,
    canvas: RenderCanvas,
) -> io::Result<PathBuf> {
    fs::create_dir_all(workdir)?;
    let path = workdir.join(format!(
        "caption-{:04}-{:.3}s.ass",
        sequence,
        title.start_s.max(0.0)
    ));
    let body = build_ass_document(title, canvas);
    fs::write(&path, body)?;
    Ok(path)
}

/// Render one editable subtitle track to a single ASS sidecar.
pub(crate) fn render_subtitle_track_ass_file(
    track: &SubtitleTrack,
    workdir: &Path,
    sequence: usize,
    canvas: RenderCanvas,
) -> io::Result<PathBuf> {
    fs::create_dir_all(workdir)?;
    let path = workdir.join(format!("subtitle-track-{sequence:04}.ass"));
    let body = build_subtitle_track_ass_document(track, canvas);
    fs::write(&path, body)?;
    Ok(path)
}

/// Build the ASS subtitle document for a captioned title.
///
/// Layout:
/// - One global `[Script Info]` header sized to the render canvas.
/// - One `[V4+ Styles]` row matching the title's font/weight/color.
/// - One or more `Dialogue:` lines. Word-timed captions carry
///   karaoke `\k<centiseconds>` tags for libass reveal; whole-cue
///   captions emit a single plain Dialogue covering the full span.
fn build_ass_document(title: &TitlePlan, canvas: RenderCanvas) -> String {
    let mut out = String::new();
    push_script_info(&mut out, canvas);
    push_styles(&mut out, title);
    push_events(&mut out, title);
    out
}

fn build_subtitle_track_ass_document(track: &SubtitleTrack, canvas: RenderCanvas) -> String {
    let mut out = String::new();
    push_script_info(&mut out, canvas);
    push_default_subtitle_styles(&mut out);
    push_subtitle_track_events(&mut out, track);
    out
}

fn push_script_info(out: &mut String, canvas: RenderCanvas) {
    out.push_str("[Script Info]\n");
    out.push_str("; Generated by awidat-render libass caption path\n");
    out.push_str("ScriptType: v4.00+\n");
    out.push_str(&format!("PlayResX: {}\n", canvas.width));
    out.push_str(&format!("PlayResY: {}\n", canvas.height));
    out.push_str("WrapStyle: 0\n");
    out.push_str("ScaledBorderAndShadow: yes\n");
    out.push('\n');
}

fn push_styles(out: &mut String, title: &TitlePlan) {
    out.push_str("[V4+ Styles]\n");
    out.push_str(
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, \
         BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, \
         BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n",
    );

    // Derive style fields — `caption_style` overrides legacy title fields when present.
    let (bold_flag, primary, border_style, back) = if let Some(style) = &title.caption_style {
        let bold = if style.weight == CaptionRenderWeight::Bold {
            -1i32
        } else {
            0i32
        };
        let primary_col = hex_to_ass_color(&style.primary_color);
        let (bs, back_col) = match &style.background {
            CaptionRenderBackground::Box { color, opacity } => {
                // ASS alpha is inverted: 0x00 = opaque, 0xFF = transparent.
                let aa = 255u8 - opacity;
                let trimmed = color.trim().trim_start_matches('#');
                let parse = |start: usize| {
                    u8::from_str_radix(trimmed.get(start..start + 2).unwrap_or("00"), 16)
                        .unwrap_or(0)
                };
                let (r, g, b) = (parse(0), parse(2), parse(4));
                let back_col = format!("&H{aa:02X}{b:02X}{g:02X}{r:02X}");
                (3i32, back_col)
            }
            CaptionRenderBackground::None => (1i32, "&H80000000".to_string()),
        };
        (bold, primary_col, bs, back_col)
    } else {
        // Legacy path: derive from TitlePlan's own fields — unchanged.
        let bold = if matches!(title.font_weight, TitleWeight::Bold) {
            -1i32
        } else {
            0i32
        };
        (
            bold,
            hex_to_ass_color(&title.color),
            1i32,
            "&H80000000".to_string(),
        )
    };

    // Karaoke fill secondary colour: the "unread" word state.
    // libass paints PrimaryColour on already-spoken words and
    // SecondaryColour on the upcoming ones.
    let secondary = "&H00FFFFFF";
    let outline = "&H00000000";
    // Vertical alignment: bottom = 2, center = 5, top = 8. These
    // numbers are libass numpad-style.
    let alignment = match title.position {
        TitlePosition::Top => 8,
        TitlePosition::Center => 5,
        TitlePosition::Bottom => 2,
    };
    let layout = CaptionLayoutProfile::for_title(title);
    let margin_v = match title.position {
        TitlePosition::Top => layout.margin_v_top,
        TitlePosition::Center => 0,
        TitlePosition::Bottom => layout.margin_v_bottom,
    };
    // caption_style.font_size is authoritative when a style is present;
    // fall back to title.font_size for the legacy path.
    let size = title
        .caption_style
        .as_ref()
        .map(|s| s.font_size)
        .unwrap_or(title.font_size);

    out.push_str(&format!(
        "Style: Caption,{font},{size},{primary},{secondary},{outline},{back},\
         {bold},0,0,0,100,100,0,0,{border_style},3,2,{alignment},{margin_l},{margin_r},{margin_v},1\n",
        font = default_caption_font_name(),
        size = size,
        primary = primary,
        secondary = secondary,
        outline = outline,
        back = back,
        bold = bold_flag,
        border_style = border_style,
        alignment = alignment,
        margin_l = layout.margin_l,
        margin_r = layout.margin_r,
        margin_v = margin_v,
    ));
    out.push('\n');
}

fn push_default_subtitle_styles(out: &mut String) {
    out.push_str("[V4+ Styles]\n");
    out.push_str(
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, \
         BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, \
         BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n",
    );
    out.push_str(&format!(
        "Style: Caption,{font},56,&H00FFFFFF,&H00FFFFFF,&H00000000,&H80000000,\
         -1,0,0,0,100,100,0,0,1,3,2,2,80,80,162,1\n",
        font = default_caption_font_name(),
    ));
    out.push('\n');
}

fn push_events(out: &mut String, title: &TitlePlan) {
    out.push_str("[Events]\n");
    out.push_str(
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n",
    );
    let dialogues = build_dialogue_lines(title);
    for dialogue in dialogues {
        out.push_str(&dialogue);
        out.push('\n');
    }
}

fn push_subtitle_track_events(out: &mut String, track: &SubtitleTrack) {
    out.push_str("[Events]\n");
    out.push_str(
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n",
    );
    for cue in track.cues.iter().filter(|cue| {
        cue.start_s.is_finite()
            && cue.end_s.is_finite()
            && cue.end_s > cue.start_s
            && !cue.text.trim().is_empty()
    }) {
        out.push_str(&format!(
            "Dialogue: 0,{start},{end},Caption,,0,0,0,,{text}\n",
            start = format_ass_time(cue.start_s),
            end = format_ass_time(cue.end_s),
            text = wrap_plain_subtitle_text(&cue.text),
        ));
    }
}

/// Word-wrap already-escaped caption text to <= max_chars_per_line per visible
/// line, inserting ASS `\N` hard breaks. Honors the layout width (unlike the
/// fixed-32 wrap_plain_subtitle_text).
fn wrap_caption_text(escaped: &str, max_chars_per_line: usize) -> String {
    let mut out = String::new();
    let mut visible = 0usize;
    for word in escaped.split_whitespace() {
        let n = word.chars().count();
        if visible > 0 && visible + 1 + n > max_chars_per_line {
            out.push_str("\\N");
            visible = 0;
        } else if visible > 0 {
            out.push(' ');
            visible += 1;
        }
        out.push_str(word);
        visible += n;
    }
    out
}

fn wrap_plain_subtitle_text(input: &str) -> String {
    let mut out = String::new();
    let mut visible_line_chars = 0usize;
    for raw_word in input.split_whitespace() {
        let next_chars = raw_word.chars().count();
        if visible_line_chars > 0 && visible_line_chars + 1 + next_chars > 32 {
            out.push_str("\\N");
            visible_line_chars = 0;
        } else if visible_line_chars > 0 {
            out.push(' ');
            visible_line_chars += 1;
        }
        out.push_str(&escape_ass_text(raw_word));
        visible_line_chars += next_chars;
    }
    if out.is_empty() {
        escape_ass_text(input)
    } else {
        out
    }
}

/// Which line of a cue this Dialogue is, for placing entrance/exit tags.
// `First`, `Middle`, and `Last` are reserved for multi-line split-cue
// rendering (future task); only `Sole` is wired today.
#[allow(dead_code)]
#[derive(Clone, Copy, PartialEq)]
enum CueLineRole {
    Sole,
    First,
    Middle,
    Last,
}

/// Leading ASS override block for entrance/exit motion on one Dialogue line.
/// `dur_cs` = the line's [start,end] span in centiseconds. Entrance on
/// Sole|First; exit on Sole|Last. Scale + fade only (alignment-compatible);
/// slide/float handled elsewhere. Returns "" when nothing applies.
fn motion_override(
    motion: crate::timeline::CaptionRenderMotion,
    role: CueLineRole,
    dur_cs: i64,
) -> String {
    use crate::timeline::{CaptionRenderEntrance as E, CaptionRenderExit as X};
    let dur_ms = (dur_cs * 10).max(1);
    let mut init = String::new();
    let mut anim = String::new();
    let mut fad_in: i64 = 0;
    let mut fad_out: i64 = 0;
    let entrance_here = matches!(role, CueLineRole::Sole | CueLineRole::First);
    let exit_here = matches!(role, CueLineRole::Sole | CueLineRole::Last);
    if entrance_here {
        match motion.entrance {
            E::PopIn => {
                init.push_str("\\fscx80\\fscy80");
                anim.push_str("\\t(0,120,\\fscx103\\fscy103)\\t(120,170,\\fscx100\\fscy100)");
            }
            E::FadeIn => fad_in = 150,
            E::SlideUp | E::None => {}
        }
    }
    if exit_here {
        match motion.exit {
            X::PopOut => {
                let s = (dur_ms - 150).max(0);
                anim.push_str(&format!("\\t({s},{dur_ms},\\fscx80\\fscy80)"));
            }
            X::FadeOut => fad_out = 150,
            X::SlideDown | X::None => {}
        }
    }
    if fad_in > 0 || fad_out > 0 {
        anim.push_str(&format!("\\fad({fad_in},{fad_out})"));
    }
    if init.is_empty() && anim.is_empty() {
        return String::new();
    }
    format!("{{{init}{anim}}}")
}

/// Synthesize one Dialogue line per "step" (cumulative word
/// prefix). Each line spans the full title window so the karaoke
/// `\k` durations inside paint reveal in sync with the transcript.
///
/// Why one line and not one-per-word: libass `\k` tags chain
/// within a single Dialogue, painting words in PrimaryColour as
/// their `\k` duration elapses. That's the karaoke reveal we want.
fn build_dialogue_lines(title: &TitlePlan) -> Vec<String> {
    // CaptionRenderMotion is Copy — extract once for use in all branches.
    let motion = title.caption_style.as_ref().map(|s| s.motion);

    let words: Vec<&crate::timeline::CaptionWordTiming> = title
        .word_timings
        .iter()
        .filter(|w| {
            !w.text.trim().is_empty()
                && w.start_s.is_finite()
                && w.end_s.is_finite()
                && w.end_s >= w.start_s
        })
        .collect();

    // ── Active-word-pop: needs both the reveal flag, a highlight color, and
    //   word timings. When all three are present, emit one Dialogue per word
    //   spanning [word.start_s, word.end_s]; the active word gets the
    //   highlight color inline, all others render in the Style's PrimaryColour.
    //   If any condition is absent, fall through to the whole-cue path below.
    let style = title.caption_style.as_ref();
    let active_pop_style = style.filter(|s| {
        matches!(
            s.reveal,
            crate::timeline::CaptionRenderReveal::ActiveWordPop
        ) && s.highlight_color.is_some()
            && !words.is_empty()
    });
    if let Some(s) = active_pop_style {
        // SAFETY: the filter above requires `highlight_color.is_some()`.
        // Fall back to primary so the caption is still visible if the
        // invariant is ever violated; this branch should never execute.
        let hi_hex_owned;
        let hi_hex: &str = match s.highlight_color.as_deref() {
            Some(c) => c,
            None => {
                hi_hex_owned = s.primary_color.clone();
                &hi_hex_owned
            }
        };
        let primary_col = hex_to_ass_color(&s.primary_color);
        let hi_col = hex_to_ass_color(hi_hex);
        let mut dialogues = Vec::with_capacity(words.len());
        for (active_idx, active_word) in words.iter().enumerate() {
            let mut line = String::new();
            for (j, w) in words.iter().enumerate() {
                if j > 0 {
                    line.push(' ');
                }
                let raw = w.text.trim();
                let cased = apply_casing(raw, title);
                let escaped = escape_ass_text(&cased);
                if j == active_idx {
                    // Wrap active word: set highlight, then restore primary after.
                    line.push_str(&format!("{{\\c{hi_col}}}{escaped}{{\\c{primary_col}}}"));
                } else {
                    line.push_str(&escaped);
                }
            }
            let start = format_ass_time(active_word.start_s);
            let end = format_ass_time(active_word.end_s);
            dialogues.push(format!("Dialogue: 0,{start},{end},Caption,,0,0,0,,{line}"));
        }
        return dialogues;
    }

    // ── Whole-cue branch (no word timings) ───────────────────────────────────
    if words.is_empty() {
        let raw_text = title.text.trim();
        if raw_text.is_empty() {
            return Vec::new();
        }
        let cased = apply_casing(raw_text, title);
        let layout = CaptionLayoutProfile::for_title(title);
        let wrapped = wrap_caption_text(&escape_ass_text(&cased), layout.max_chars_per_line);
        let start = format_ass_time(title.start_s.max(0.0));
        let end = format_ass_time(title.end_s.max(title.start_s));
        let dur_cs = seconds_to_centiseconds((title.end_s - title.start_s).max(0.0)) as i64;
        let mv = motion
            .map(|m| motion_override(m, CueLineRole::Sole, dur_cs))
            .unwrap_or_default();
        return vec![format!(
            "Dialogue: 0,{start},{end},Caption,,0,0,0,,{mv}{wrapped}"
        )];
    }

    // ── Word-by-word karaoke branch ───────────────────────────────────────────
    let start = format_ass_time(title.start_s.max(0.0));
    let end = format_ass_time(title.end_s.max(title.start_s));

    // Build the karaoke run for one Dialogue line. Lead-in (any gap
    // between title.start_s and the first word) is encoded as a
    // leading `\k` on an empty group so libass holds the line idle.
    let mut text = String::new();
    let layout = CaptionLayoutProfile::for_title(title);
    let mut visible_line_chars = 0usize;
    let first_word_start = words.first().map(|w| w.start_s).unwrap_or(title.start_s);
    let lead_in_cs = seconds_to_centiseconds((first_word_start - title.start_s).max(0.0));
    if lead_in_cs > 0 {
        text.push_str(&format!("{{\\k{lead_in_cs}}}"));
    }
    for (idx, word) in words.iter().enumerate() {
        let dur_cs = seconds_to_centiseconds((word.end_s - word.start_s).max(0.0));
        let raw_glyphs = word.text.trim();
        let cased_glyphs = apply_casing(raw_glyphs, title);
        let glyphs = escape_ass_text(&cased_glyphs);
        if idx > 0 {
            let next_chars = raw_glyphs.chars().count();
            if visible_line_chars > 0
                && visible_line_chars + 1 + next_chars > layout.max_chars_per_line
            {
                text.push_str("\\N");
                visible_line_chars = 0;
            } else {
                text.push(' ');
                visible_line_chars += 1;
            }
        }
        text.push_str(&format!("{{\\k{dur_cs}}}{glyphs}"));
        visible_line_chars += raw_glyphs.chars().count();
    }

    let dur_cs = seconds_to_centiseconds((title.end_s - title.start_s).max(0.0)) as i64;
    let mv = motion
        .map(|m| motion_override(m, CueLineRole::Sole, dur_cs))
        .unwrap_or_default();
    vec![format!("Dialogue: 0,{start},{end},Caption,,0,0,0,,{mv}{text}",)]
}

/// ASS uses `H:MM:SS.cc` (centiseconds). Source seconds are master
/// timeline floats. Clamp to >= 0 and to 9:59:59.99 to avoid
/// pathological negative values upstream from breaking the format.
pub(crate) fn format_ass_time(seconds: f64) -> String {
    let mut total_cs = (seconds.max(0.0) * 100.0).round() as i64;
    let max_cs: i64 = 9 * 360_000 + 59 * 6_000 + 59 * 100 + 99;
    if total_cs > max_cs {
        total_cs = max_cs;
    }
    let cs = total_cs % 100;
    let total_s = total_cs / 100;
    let s = total_s % 60;
    let total_m = total_s / 60;
    let m = total_m % 60;
    let h = total_m / 60;
    format!("{h}:{m:02}:{s:02}.{cs:02}")
}

fn seconds_to_centiseconds(seconds: f64) -> u32 {
    if !seconds.is_finite() || seconds <= 0.0 {
        return 0;
    }
    (seconds * 100.0).round().max(0.0) as u32
}

/// Convert `#RRGGBB` (or `#RRGGBBAA`) into ASS `&HAABBGGRR` form.
/// libass uses 0xAABBGGRR with alpha as "transparency" (0x00 =
/// opaque, 0xFF = fully transparent), the inverse of what most
/// graphics layers ship. Fall back to opaque white on parse error
/// so the caption is still visible.
pub(crate) fn hex_to_ass_color(hex: &str) -> String {
    let trimmed = hex.trim().trim_start_matches('#');
    let parse = |start: usize| u8::from_str_radix(trimmed.get(start..start + 2)?, 16).ok();
    let (r, g, b, a) = match trimmed.len() {
        6 => (parse(0), parse(2), parse(4), Some(0x00)),
        8 => (
            parse(0),
            parse(2),
            parse(4),
            parse(6).map(|alpha| 0xFF - alpha),
        ),
        _ => (None, None, None, None),
    };
    match (r, g, b, a) {
        (Some(r), Some(g), Some(b), Some(a)) => {
            format!("&H{a:02X}{b:02X}{g:02X}{r:02X}")
        }
        _ => "&H00FFFFFF".to_string(),
    }
}

/// Apply casing to text based on the title's `caption_style`. When
/// `caption_style` is absent or casing is `AsIs`, returns the input
/// unchanged. When casing is `Upper`, uppercases the whole string.
fn apply_casing(text: &str, title: &TitlePlan) -> String {
    match title.caption_style.as_ref().map(|s| &s.casing) {
        Some(CaptionRenderCasing::Upper) => text.to_uppercase(),
        _ => text.to_owned(),
    }
}

/// libass parses `{...}` as override blocks, `\` as escape, and
/// newlines as soft breaks. Escape the bare characters; we'd
/// rather caption text render as literal punctuation than as
/// drawtext-style filter syntax.
fn escape_ass_text(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '{' => out.push_str("\\{"),
            '}' => out.push_str("\\}"),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\N"),
            _ => out.push(ch),
        }
    }
    out
}

/// Environment variable that, when set and non-empty, short-circuits
/// the host font probe and pins the ASS `Fontname` to whatever the
/// caller wants. Documented as `AWIDAT_CAPTION_FONT` for users.
const CAPTION_FONT_ENV: &str = "AWIDAT_CAPTION_FONT";

/// Ordered probe list of `(font_file_on_disk, family_name_for_ass)`.
/// We check each file path; the first one that resolves means the
/// host ships that family, so libass's fontconfig step at render
/// time will be able to find it too. Last entry is the universal
/// libass fallback alias `"Sans Serif"` (always returned if nothing
/// else hit) — libass treats this as a generic family name.
///
/// Layered platform-first so the most idiomatic choice wins on each
/// host: macOS → Helvetica Neue, Linux → DejaVu Sans, Windows →
/// Segoe UI. "Inter" and "Arial" are cross-platform fallbacks.
const CAPTION_FONT_CANDIDATES: &[(&str, &str)] = &[
    // macOS
    ("/System/Library/Fonts/HelveticaNeue.ttc", "Helvetica Neue"),
    ("/System/Library/Fonts/Helvetica.ttc", "Helvetica"),
    ("/Library/Fonts/Inter.ttc", "Inter"),
    ("/System/Library/Fonts/Supplemental/Arial.ttf", "Arial"),
    // Linux
    (
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "DejaVu Sans",
    ),
    ("/usr/share/fonts/TTF/DejaVuSans.ttf", "DejaVu Sans"),
    (
        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
        "Liberation Sans",
    ),
    ("/usr/share/fonts/inter/Inter-Regular.ttf", "Inter"),
    // Windows
    ("C:\\Windows\\Fonts\\segoeui.ttf", "Segoe UI"),
    ("C:\\Windows\\Fonts\\arial.ttf", "Arial"),
];

/// Universal libass fallback when no probed candidate hits. libass
/// treats `"Sans Serif"` as a generic family alias, so this still
/// produces *some* rendering rather than dropping captions on a
/// stripped-down container.
const CAPTION_FONT_FALLBACK: &str = "Sans Serif";

/// Resolve the ASS `Fontname` to write into the `Style:` row.
///
/// Order of resolution:
///   1. `env_getter("AWIDAT_CAPTION_FONT")` returning `Some(name)`
///      with a non-empty (after trim) value — that wins, no probing.
///   2. First entry in [`CAPTION_FONT_CANDIDATES`] whose file path
///      exists on disk → return its family name.
///   3. [`CAPTION_FONT_FALLBACK`] (`"Sans Serif"`).
///
/// Injecting `env_getter` (instead of calling `std::env::var`
/// directly) lets tests drive every branch without touching the
/// process env — `std::env::set_var` is `unsafe` in edition 2024
/// and the workspace forbids `unsafe`.
pub fn resolve_caption_font_name<F>(env_getter: F) -> String
where
    F: Fn(&str) -> Option<String>,
{
    if let Some(raw) = env_getter(CAPTION_FONT_ENV) {
        let trimmed = raw.trim();
        if !trimmed.is_empty() {
            return trimmed.to_string();
        }
    }
    for (path, family) in CAPTION_FONT_CANDIDATES {
        if std::path::Path::new(path).is_file() {
            return (*family).to_string();
        }
    }
    CAPTION_FONT_FALLBACK.to_string()
}

/// Production wrapper around [`resolve_caption_font_name`] that
/// reads `AWIDAT_CAPTION_FONT` from the real process env.
pub fn default_caption_font_name() -> String {
    resolve_caption_font_name(|key| std::env::var(key).ok())
}

/// Test-visible re-export of [`build_ass_document`] using the default 1920×1080
/// canvas so existing callers stay unchanged.
pub fn build_ass_document_for_test(title: &TitlePlan) -> String {
    build_ass_document(title, RenderCanvas::default())
}

/// Test helper: build an ASS document with an explicit render canvas.
/// Use this to assert that `PlayResX`/`PlayResY` match the canvas dimensions.
#[cfg(test)]
pub fn build_ass_document_with_canvas(title: &TitlePlan, canvas: RenderCanvas) -> String {
    build_ass_document(title, canvas)
}

/// ffmpeg's `subtitles=` filter parses its argument as a key/value
/// list. Single quotes wrap the path so spaces and `=` inside are
/// safe, and embedded single quotes are escaped as `\\\'` per
/// ffmpeg filter quoting rules.
pub(crate) fn ffmpeg_subtitles_filter_arg(path: &Path) -> String {
    let display = path.to_string_lossy();
    let escaped = display.replace('\\', "\\\\").replace('\'', "\\\\\\'");
    format!("subtitles='{escaped}'")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::timeline::{
        CaptionWordTiming, TextReveal, TitleAnimation, TitlePlan, TitlePosition, TitleWeight,
    };

    fn caption_title(text: &str, word_timings: Vec<CaptionWordTiming>) -> TitlePlan {
        TitlePlan {
            text: text.into(),
            start_s: 1.0,
            end_s: 3.0,
            position: TitlePosition::Bottom,
            font_size: 44,
            color: "#FFFFFF".into(),
            font_weight: TitleWeight::Normal,
            animation: TitleAnimation::None,
            phases: None,
            reveal: TextReveal::None,
            role: "caption".into(),
            safe_area: Some("standard".into()),
            rich_segments: Vec::new(),
            word_timings,
            animations: Vec::new(),
            font_path: None,
            font_family: None,
            caption_style: None,
        }
    }

    fn caption_with_words() -> TitlePlan {
        TitlePlan {
            text: "hello world".into(),
            start_s: 1.0,
            end_s: 2.5,
            position: TitlePosition::Bottom,
            font_size: 64,
            color: "#FFFFFF".into(),
            font_weight: TitleWeight::Bold,
            animation: TitleAnimation::None,
            phases: None,
            reveal: TextReveal::None,
            role: "caption".into(),
            safe_area: None,
            rich_segments: Vec::new(),
            word_timings: vec![
                CaptionWordTiming {
                    text: "hello".into(),
                    start_s: 1.0,
                    end_s: 1.6,
                },
                CaptionWordTiming {
                    text: "world".into(),
                    start_s: 1.6,
                    end_s: 2.4,
                },
            ],
            animations: Vec::new(),
            font_path: None,
            font_family: None,
            caption_style: None,
        }
    }

    #[test]
    fn eligibility_requires_caption_role() {
        let mut title = caption_with_words();
        assert!(is_libass_eligible(&title));
        title.role = "title".into();
        assert!(!is_libass_eligible(&title));
        // Whole-cue captions (no word timings) are still eligible — they
        // render via the plain Dialogue branch rather than karaoke.
        title.role = "caption".into();
        title.word_timings.clear();
        assert!(
            is_libass_eligible(&title),
            "whole-cue caption must still use libass"
        );
    }

    #[test]
    fn ass_document_contains_karaoke_tags_and_word_text() {
        let title = caption_with_words();
        let doc = build_ass_document(&title, RenderCanvas::default());
        assert!(doc.contains("[Script Info]"));
        assert!(doc.contains("[V4+ Styles]"));
        assert!(doc.contains("[Events]"));
        assert!(doc.contains("\\k"), "missing karaoke tag in: {doc}");
        assert!(doc.contains("hello"));
        assert!(doc.contains("world"));
        // Karaoke durations should be word durations in centiseconds
        // (1.6 - 1.0 = 60cs ; 2.4 - 1.6 = 80cs).
        assert!(
            doc.contains("\\k60"),
            "expected hello duration 60cs in: {doc}"
        );
        assert!(
            doc.contains("\\k80"),
            "expected world duration 80cs in: {doc}"
        );
    }

    #[test]
    fn mobile_safe_area_caption_uses_tighter_layout_profile() {
        let mut title = caption_with_words();
        title.safe_area = Some("mobile".into());
        title.word_timings = vec![
            CaptionWordTiming {
                text: "This".into(),
                start_s: 1.0,
                end_s: 1.1,
            },
            CaptionWordTiming {
                text: "mobile".into(),
                start_s: 1.1,
                end_s: 1.2,
            },
            CaptionWordTiming {
                text: "caption".into(),
                start_s: 1.2,
                end_s: 1.3,
            },
            CaptionWordTiming {
                text: "wraps".into(),
                start_s: 1.3,
                end_s: 1.4,
            },
            CaptionWordTiming {
                text: "cleanly".into(),
                start_s: 1.4,
                end_s: 1.5,
            },
        ];

        let doc = build_ass_document(&title, RenderCanvas::default());

        assert!(
            doc.contains(",2,160,160,216,1"),
            "mobile safe-area profile should increase side and bottom margins: {doc}"
        );
        assert!(
            doc.contains("\\N"),
            "mobile caption profile should wrap long karaoke text with ASS line breaks: {doc}"
        );
    }

    #[test]
    fn default_caption_layout_allows_wider_lines_than_mobile() {
        let mut title = caption_with_words();
        title.word_timings = vec![
            CaptionWordTiming {
                text: "This".into(),
                start_s: 1.0,
                end_s: 1.1,
            },
            CaptionWordTiming {
                text: "desktop".into(),
                start_s: 1.1,
                end_s: 1.2,
            },
            CaptionWordTiming {
                text: "caption".into(),
                start_s: 1.2,
                end_s: 1.3,
            },
            CaptionWordTiming {
                text: "wraps".into(),
                start_s: 1.3,
                end_s: 1.4,
            },
        ];

        let doc = build_ass_document(&title, RenderCanvas::default());

        assert!(doc.contains(",2,80,80,162,1"));
        assert!(
            !doc.contains("\\N"),
            "default layout should keep this caption on one line: {doc}"
        );
    }

    #[test]
    fn hex_to_ass_color_uses_bgr_with_alpha() {
        // #FF0000 (red) → &H000000FF (alpha 00 = opaque, BGR=0000FF).
        assert_eq!(hex_to_ass_color("#FF0000"), "&H000000FF");
        // White stays white in any channel order.
        assert_eq!(hex_to_ass_color("#FFFFFF"), "&H00FFFFFF");
        // Bad input falls back to opaque white.
        assert_eq!(hex_to_ass_color("not-a-color"), "&H00FFFFFF");
    }

    #[test]
    fn format_ass_time_uses_centiseconds() {
        assert_eq!(format_ass_time(0.0), "0:00:00.00");
        assert_eq!(format_ass_time(1.235), "0:00:01.24");
        assert_eq!(format_ass_time(3661.5), "1:01:01.50");
    }

    #[test]
    fn escape_ass_text_neutralizes_override_braces() {
        assert_eq!(escape_ass_text("hi {there}"), "hi \\{there\\}");
        assert_eq!(escape_ass_text("a\\b"), "a\\\\b");
    }

    #[test]
    fn render_ass_file_writes_to_workdir() {
        let dir = tempfile::tempdir().unwrap();
        let title = caption_with_words();
        let path = render_ass_file(&title, dir.path(), 0, RenderCanvas::default()).unwrap();
        assert!(path.exists());
        assert!(path.extension().and_then(|e| e.to_str()) == Some("ass"));
        let body = fs::read_to_string(&path).unwrap();
        assert!(body.contains("\\k"));
    }

    #[test]
    fn caption_without_word_timings_is_libass_eligible() {
        let t = caption_title("hello world", vec![]);
        assert!(
            is_libass_eligible(&t),
            "whole-cue captions must use libass, not drawtext"
        );
    }

    #[test]
    fn whole_cue_caption_emits_one_dialogue_with_full_text() {
        let t = caption_title("the rise of solo entrepreneurs", vec![]);
        let doc = build_ass_document(&t, RenderCanvas::default());
        let dialogues: Vec<&str> = doc.lines().filter(|l| l.starts_with("Dialogue:")).collect();
        assert_eq!(
            dialogues.len(),
            1,
            "exactly one whole-cue dialogue, got: {dialogues:?}"
        );
        assert!(doc.contains("rise") && doc.contains("entrepreneurs"));
        assert!(
            !dialogues[0].contains("\\k"),
            "whole-cue must not emit karaoke \\k tags"
        );
    }

    #[test]
    fn lower_third_safe_area_raises_bottom_margin() {
        let mut t = caption_title("x", vec![]);
        t.safe_area = Some("lower_third".into());
        let raised = CaptionLayoutProfile::for_title(&t);
        t.safe_area = Some("standard".into());
        let standard = CaptionLayoutProfile::for_title(&t);
        assert_eq!(
            raised.margin_v_bottom, 300,
            "lower_third clears the banner band"
        );
        assert_eq!(standard.margin_v_bottom, 162, "standard unchanged");
        assert!(raised.margin_v_bottom > standard.margin_v_bottom);
    }

    fn styled(
        spec: crate::timeline::CaptionRenderStyle,
        text: &str,
        wt: Vec<crate::timeline::CaptionWordTiming>,
    ) -> crate::timeline::TitlePlan {
        let mut t = caption_title(text, wt);
        t.caption_style = Some(spec);
        t
    }

    #[test]
    fn upper_casing_uppercases_dialogue_text() {
        use crate::timeline::*;
        let spec = CaptionRenderStyle {
            font_size: 64,
            weight: CaptionRenderWeight::Bold,
            casing: CaptionRenderCasing::Upper,
            primary_color: "#FFFFFF".into(),
            highlight_color: None,
            reveal: CaptionRenderReveal::WholeCue,
            background: CaptionRenderBackground::None,
            motion: CaptionRenderMotion::default(),
        };
        let doc = build_ass_document(&styled(spec, "rise of solo", vec![]), RenderCanvas::default());
        assert!(
            doc.contains("RISE OF SOLO"),
            "Upper casing must uppercase text: {doc}"
        );
    }

    #[test]
    fn boxed_background_uses_opaque_border_style() {
        use crate::timeline::*;
        let spec = CaptionRenderStyle {
            font_size: 48,
            weight: CaptionRenderWeight::Normal,
            casing: CaptionRenderCasing::AsIs,
            primary_color: "#FFFFFF".into(),
            highlight_color: None,
            reveal: CaptionRenderReveal::WholeCue,
            background: CaptionRenderBackground::Box {
                color: "#000000".into(),
                opacity: 153,
            },
            motion: CaptionRenderMotion::default(),
        };
        let doc = build_ass_document(&styled(spec, "hi", vec![]), RenderCanvas::default());
        let style_line = doc
            .lines()
            .find(|l| l.starts_with("Style: Caption"))
            .expect("style row");
        let fields: Vec<&str> = style_line
            .trim_start_matches("Style: ")
            .split(',')
            .collect();
        // fields[0]="Caption"; BorderStyle is the 16th field => index 15.
        assert_eq!(
            fields[15], "3",
            "boxed background must set BorderStyle=3: {style_line}"
        );
    }

    #[test]
    fn bold_weight_sets_bold_flag() {
        use crate::timeline::*;
        let spec = CaptionRenderStyle {
            font_size: 64,
            weight: CaptionRenderWeight::Bold,
            casing: CaptionRenderCasing::AsIs,
            primary_color: "#FFFFFF".into(),
            highlight_color: None,
            reveal: CaptionRenderReveal::WholeCue,
            background: CaptionRenderBackground::None,
            motion: CaptionRenderMotion::default(),
        };
        let doc = build_ass_document(&styled(spec, "hi", vec![]), RenderCanvas::default());
        let fields: Vec<&str> = doc
            .lines()
            .find(|l| l.starts_with("Style: Caption"))
            .unwrap()
            .trim_start_matches("Style: ")
            .split(',')
            .collect();
        assert_eq!(fields[7], "-1", "Bold flag must be -1 for Bold weight"); // Bold is the 8th field
    }

    #[test]
    fn active_word_pop_emits_one_dialogue_per_word_with_one_highlight() {
        use crate::timeline::*;
        let spec = CaptionRenderStyle {
            font_size: 64,
            weight: CaptionRenderWeight::Bold,
            casing: CaptionRenderCasing::Upper,
            primary_color: "#FFFFFF".into(),
            highlight_color: Some("#FFE000".into()),
            reveal: CaptionRenderReveal::ActiveWordPop,
            background: CaptionRenderBackground::None,
            motion: CaptionRenderMotion::default(),
        };
        let wt = vec![
            CaptionWordTiming {
                text: "five".into(),
                start_s: 1.0,
                end_s: 1.4,
            },
            CaptionWordTiming {
                text: "ten".into(),
                start_s: 1.4,
                end_s: 2.0,
            },
        ];
        let doc = build_ass_document(&styled(spec, "five ten", wt), RenderCanvas::default());
        let dialogues: Vec<&str> = doc.lines().filter(|l| l.starts_with("Dialogue:")).collect();
        assert_eq!(dialogues.len(), 2, "one dialogue per word: {dialogues:?}");
        // full (uppercased) line shown in each
        assert!(dialogues[0].contains("FIVE") && dialogues[0].contains("TEN"));
        // exactly one highlight color override marker per dialogue line
        let hi = hex_to_ass_color("#FFE000");
        assert_eq!(
            dialogues[0].matches(&hi).count(),
            1,
            "exactly one highlighted word: {}",
            dialogues[0]
        );
        // the highlighted word in dialogue[0] is the first word; dialogue[1] highlights the second
        assert_eq!(dialogues[1].matches(&hi).count(), 1);
        // timing spans the word window
        assert!(
            dialogues[0].contains(&format_ass_time(1.0))
                && dialogues[0].contains(&format_ass_time(1.4))
        );
    }

    #[test]
    fn active_word_pop_without_timings_degrades_to_whole_cue() {
        use crate::timeline::*;
        let spec = CaptionRenderStyle {
            font_size: 64,
            weight: CaptionRenderWeight::Bold,
            casing: CaptionRenderCasing::AsIs,
            primary_color: "#FFFFFF".into(),
            highlight_color: Some("#FFE000".into()),
            reveal: CaptionRenderReveal::ActiveWordPop,
            background: CaptionRenderBackground::None,
            motion: CaptionRenderMotion::default(),
        };
        let doc = build_ass_document(&styled(spec, "hello world", vec![]), RenderCanvas::default());
        let n = doc.lines().filter(|l| l.starts_with("Dialogue:")).count();
        assert_eq!(n, 1, "no word timings -> single whole-cue dialogue");
    }

    #[test]
    fn ass_playres_matches_render_canvas() {
        use crate::timeline::RenderCanvas;
        let t = caption_title("hi", vec![]);
        let portrait =
            build_ass_document_with_canvas(&t, RenderCanvas { width: 1080, height: 1920 });
        assert!(
            portrait.contains("PlayResX: 1080") && portrait.contains("PlayResY: 1920"),
            "vertical canvas must drive PlayRes: {portrait}"
        );
        let landscape =
            build_ass_document_with_canvas(&t, RenderCanvas { width: 1920, height: 1080 });
        assert!(landscape.contains("PlayResX: 1920") && landscape.contains("PlayResY: 1080"));
    }

    fn motion_style(
        entrance: crate::timeline::CaptionRenderEntrance,
        exit: crate::timeline::CaptionRenderExit,
    ) -> crate::timeline::CaptionRenderStyle {
        crate::timeline::CaptionRenderStyle {
            font_size: 44,
            weight: crate::timeline::CaptionRenderWeight::Normal,
            casing: crate::timeline::CaptionRenderCasing::AsIs,
            primary_color: "#FFFFFF".into(),
            highlight_color: None,
            reveal: crate::timeline::CaptionRenderReveal::WholeCue,
            background: crate::timeline::CaptionRenderBackground::None,
            motion: crate::timeline::CaptionRenderMotion {
                entrance,
                exit,
                active_word: crate::timeline::CaptionRenderActiveWord::None,
                continuous: crate::timeline::CaptionRenderContinuous::None,
            },
        }
    }

    #[test]
    fn pop_in_entrance_emits_scale_animation_on_whole_cue() {
        use crate::timeline::*;
        let mut t = caption_title("hello", vec![]);
        t.caption_style = Some(motion_style(CaptionRenderEntrance::PopIn, CaptionRenderExit::None));
        let doc = build_ass_document(&t, RenderCanvas::default());
        let d = doc.lines().find(|l| l.starts_with("Dialogue:")).unwrap();
        assert!(d.contains("\\fscx") && d.contains("\\t("), "PopIn must emit a scale \\t: {d}");
    }

    #[test]
    fn fade_in_out_emits_fad_on_whole_cue() {
        use crate::timeline::*;
        let mut t = caption_title("hello", vec![]);
        t.caption_style = Some(motion_style(CaptionRenderEntrance::FadeIn, CaptionRenderExit::FadeOut));
        let d = build_ass_document(&t, RenderCanvas::default())
            .lines()
            .find(|l| l.starts_with("Dialogue:"))
            .unwrap()
            .to_string();
        assert!(d.contains("\\fad("), "fade must emit \\fad: {d}");
    }

    #[test]
    fn no_motion_whole_cue_is_unchanged() {
        let t = caption_title("hello world", vec![]); // caption_style None
        let doc = build_ass_document(&t, RenderCanvas::default());
        let d = doc.lines().find(|l| l.starts_with("Dialogue:")).unwrap();
        assert!(!d.contains("\\t(") && !d.contains("\\fad("), "no motion -> no animation tags: {d}");
    }

    #[test]
    fn caption_style_font_size_overrides_title_font_size() {
        use crate::timeline::*;
        let spec = CaptionRenderStyle {
            font_size: 72,
            weight: CaptionRenderWeight::Bold,
            casing: CaptionRenderCasing::AsIs,
            primary_color: "#FFFFFF".into(),
            highlight_color: None,
            reveal: CaptionRenderReveal::WholeCue,
            background: CaptionRenderBackground::None,
            motion: CaptionRenderMotion::default(),
        };
        let mut t = styled(spec, "hi", vec![]);
        t.font_size = 30; // top-level differs; style must win
        let doc = build_ass_document(&t, RenderCanvas::default());
        let fields: Vec<&str> = doc
            .lines()
            .find(|l| l.starts_with("Style: Caption"))
            .unwrap()
            .trim_start_matches("Style: ")
            .split(',')
            .collect();
        // Format: Name, Fontname, Fontsize, ... => index 0=Name, 1=Fontname, 2=Fontsize
        assert_eq!(
            fields[2], "72",
            "caption_style.font_size must drive the Style row: {fields:?}"
        );
    }
}
