#!/usr/bin/env node
/**
 * Stage harness screenshot gate (Phase-1 Task 8, parameterized over
 * template scenes in Phase-2 Task 7).
 *
 * Boots (or reuses) the desktop dev server, then for each case in
 * CASES loads the deterministic `/stage-harness` route at a frozen
 * clock time, waits for `document.title === "stage-harness-ready"`,
 * DOM-asserts the expected overlays landed, screenshots just the
 * program-frame element, and compares it against a committed
 * per-platform golden via ffmpeg SSIM (see `scripts/ssim-compare.sh`).
 * Before capture, the video's decoded content is verified in-page
 * against a frame-0 signature (with a re-seek recovery loop) — the known
 * CI flake is the pre-seek frame remaining the video's presented frame,
 * a state observed to stick across page loads in one browser session. A
 * failing compare still gets ONE evidence-preserving recapture, from a
 * FRESH browser launch; both attempts' SSIMs are printed and the
 * attempt-1 screenshot is kept. See comments in captureCase/runCase.
 *
 * A missing per-platform golden is a hard failure so the gate can never
 * silently self-seed in CI. To seed a new platform, run once locally with
 * STAGE_GOLDEN_BOOTSTRAP=1 (or commit the screenshot CI uploads as the
 * `stage-harness-screenshots` artifact) and commit the golden.
 *
 * Template scene fixtures (`scene-lower-third.json`,
 * `scene-kinetic-text.json`) are generated by the sync tests in
 * `crates/core/tests/motion_template_goldens.rs` from
 * `expand_template` + the snapshot lowering's field mapping — do not
 * hand-edit them; regenerate with UPDATE_GOLDENS=1 there. Two
 * timestamps per template catch mid-animation states (slide-in in
 * flight vs settled; words mid-pop vs held).
 *
 * Follows the dev-server boot/reuse pattern of `tests/desktop-ui-smoke.mjs`
 * (canReachApp / ensureAppServer / stopAppServer), spawning
 * `pnpm --dir apps/desktop exec vite` when the app isn't already up.
 */

import { chromium } from "playwright";
import { strict as assert } from "node:assert";
import { spawn, execFileSync } from "node:child_process";
import { mkdirSync, existsSync, copyFileSync } from "node:fs";
import { setTimeout as delay } from "node:timers/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = fileURLToPath(new URL("../../..", import.meta.url));
const BASE_URL = process.env.SMOKE_URL ?? "http://127.0.0.1:1420/";
const APP_URL = new URL(BASE_URL);
const APP_PORT = APP_URL.port || (APP_URL.protocol === "https:" ? "443" : "80");
const SCREENSHOT_DIR = process.env.SMOKE_OUT_DIR ?? "tests/smoke";
const GOLDEN_DIR = "tests/fixtures/stage-golden";
mkdirSync(SCREENSHOT_DIR, { recursive: true });
mkdirSync(GOLDEN_DIR, { recursive: true });

const MIN_SSIM = "0.98";

/** Shared context options — the retry path launches a fresh browser and
 * must match the primary context exactly or goldens won't compare. */
const CONTEXT_OPTIONS = {
  viewport: { width: 1280, height: 720 },
  deviceScaleFactor: 1,
};

/**
 * In-page video content check threshold (mean absolute luminance
 * difference on a 32x18 downsample, 0-255 scale). Calibrated against the
 * fixture clip with ffmpeg: the stale frame (frame 0) vs itself is ~0 and
 * vs its neighbor frame 1 is 0.53, while frame 0 vs each case's target
 * frame is 2.23 (t=0.4) / 3.09 (t=0.5) / 7.53 (t=1.0) / 7.66 (t=1.5) /
 * 6.42 (t=2.0) — so 1.0 separates "still showing frame 0" from "showing
 * the seeked frame" with >= 2x margin on both sides for every case.
 */
const FRAME0_LUMA_DIFF_THRESHOLD = 1.0;
const MAX_RESEEKS = 5;

const MOTION_TITLE_SELECTOR = ".timeline-motion-scene-layer .timeline-title-overlay";
const LEGACY_TITLE_SELECTOR = ".timeline-title-layer .timeline-title-overlay";
const SHAPE_SELECTOR = ".timeline-motion-shape-rect";
const IMAGE_SELECTOR = ".timeline-motion-image";

async function overlayTexts(page, selector) {
  const layer = page.locator(selector);
  const count = await layer.count();
  const texts = [];
  for (let index = 0; index < count; index += 1) {
    texts.push((await layer.nth(index).textContent()) ?? "");
  }
  return texts;
}

async function assertOverlayCounts(page, { legacyTitles, motionTitles, shapes, images }) {
  assert.equal(
    await page.locator(LEGACY_TITLE_SELECTOR).count(),
    legacyTitles,
    `expected ${legacyTitles} legacy title overlay(s)`,
  );
  assert.equal(
    await page.locator(MOTION_TITLE_SELECTOR).count(),
    motionTitles,
    `expected ${motionTitles} motion-scene title overlay(s)`,
  );
  assert.equal(
    await page.locator(SHAPE_SELECTOR).count(),
    shapes,
    `expected ${shapes} shape overlay(s)`,
  );
  assert.equal(
    await page.locator(IMAGE_SELECTOR).count(),
    images,
    `expected ${images} image overlay(s)`,
  );
}

/** Phase-1 scene: one legacy title + one rect + one image. */
async function assertSceneBasic(page) {
  await assertOverlayCounts(page, { legacyTitles: 1, motionTitles: 0, shapes: 1, images: 1 });
  const [titleText] = await overlayTexts(page, LEGACY_TITLE_SELECTOR);
  assert.ok(titleText.includes("STAGE HARNESS"), `title overlay text mismatch: ${titleText}`);
}

/** Lower third: accent bar + name + role, at both timestamps (the bar
 * slides but never leaves its 0..5s window; both texts are staggered
 * in by 0.16s, so all three overlays exist at t=0.4 and t=2.0). */
async function assertLowerThird(page) {
  await assertOverlayCounts(page, { legacyTitles: 0, motionTitles: 2, shapes: 1, images: 0 });
  const texts = await overlayTexts(page, MOTION_TITLE_SELECTOR);
  assert.deepEqual(texts, ["Ada Lovelace", "Mathematician"], "lower-third text overlays mismatch");
}

/** Kinetic text: word layers have their own windows, so the visible
 * word set is timestamp-specific. */
function assertKineticWords(expectedWords) {
  return async (page) => {
    await assertOverlayCounts(page, {
      legacyTitles: 0,
      motionTitles: expectedWords.length,
      shapes: 0,
      images: 0,
    });
    const texts = await overlayTexts(page, MOTION_TITLE_SELECTOR);
    assert.deepEqual(texts, expectedWords, "kinetic-text word overlays mismatch");
  };
}

/**
 * Case table. `name` + `t` name the screenshot and per-platform golden
 * (`<name>-t<t>-<platform>.png`); `assertDom` pins the expected overlay
 * DOM before the screenshot is trusted.
 */
const CASES = [
  {
    name: "scene-basic",
    scene: "/fixtures/stage/scene-basic.json",
    t: "1.0",
    assertDom: assertSceneBasic,
  },
  {
    // Slide-in mid-flight: bar/name/role all inside their 0.55s
    // ease-out-cubic slide (and the texts mid fade-in).
    name: "scene-lower-third",
    scene: "/fixtures/stage/scene-lower-third.json",
    t: "0.4",
    assertDom: assertLowerThird,
  },
  {
    // Settled: slides and fades done, holding at final x / peak opacity.
    name: "scene-lower-third",
    scene: "/fixtures/stage/scene-lower-third.json",
    t: "2.0",
    assertDom: assertLowerThird,
  },
  {
    // "Ship" mid-exit-fade, "it" mid pop-in (opacity+spring scale),
    // "today" not yet started.
    name: "scene-kinetic-text",
    scene: "/fixtures/stage/scene-kinetic-text.json",
    t: "0.5",
    assertDom: assertKineticWords(["Ship", "it"]),
  },
  {
    // Earlier words exited; only "today" remains, settled.
    name: "scene-kinetic-text",
    scene: "/fixtures/stage/scene-kinetic-text.json",
    t: "1.5",
    assertDom: assertKineticWords(["today"]),
  },
];

let appServer = null;

async function canReachApp() {
  try {
    const response = await fetch(BASE_URL, { signal: AbortSignal.timeout(500) });
    return response.ok;
  } catch {
    return false;
  }
}

async function ensureAppServer() {
  if (await canReachApp()) return;

  appServer = spawn("pnpm", ["--dir", "apps/desktop", "exec", "vite", "--host", "127.0.0.1", "--port", APP_PORT, "--strictPort"], {
    cwd: REPO_ROOT,
    env: { ...process.env, BROWSER: "none", VITE_MONTAGE_SKIP_WELCOME: "1" },
    detached: process.platform !== "win32",
    stdio: ["ignore", "pipe", "pipe"],
  });

  appServer.stdout.on("data", (chunk) => process.stdout.write(chunk));
  appServer.stderr.on("data", (chunk) => process.stderr.write(chunk));

  for (let attempt = 0; attempt < 60; attempt += 1) {
    if (await canReachApp()) return;
    if (appServer.exitCode !== null) {
      throw new Error(`dev server exited before ${BASE_URL} became reachable`);
    }
    await delay(500);
  }

  throw new Error(`timed out waiting for ${BASE_URL}`);
}

async function stopAppServer() {
  if (appServer && appServer.exitCode === null) {
    const stopped = new Promise((resolve) => {
      appServer.once("exit", resolve);
    });
    if (process.platform === "win32") {
      appServer.kill("SIGTERM");
    } else {
      process.kill(-appServer.pid, "SIGTERM");
    }
    await Promise.race([stopped, delay(2000)]);
  }
}

process.on("SIGINT", () => {
  stopAppServer();
  process.exit(130);
});
process.on("SIGTERM", () => {
  stopAppServer();
  process.exit(143);
});

/** Navigate a fresh page, DOM-assert, and screenshot one case. */
async function captureCase(ctx, testCase, shotPath) {
  const { scene, t, assertDom } = testCase;
  const harnessUrl = new URL(`/stage-harness?t=${t}&scene=${scene}`, BASE_URL).toString();

  const page = await ctx.newPage();
  try {
    const errors = [];
    page.on("pageerror", (e) => errors.push(`pageerror: ${e.message}`));
    page.on("console", (m) => {
      if (m.type() === "error") errors.push(`console.error: ${m.text()}`);
    });

    await page.goto(harnessUrl, { waitUntil: "networkidle" });
    await page.waitForFunction(() => document.title === "stage-harness-ready", null, { timeout: 15000 });

    assert.deepEqual(errors, [], `harness console/page errors: ${errors.join("; ")}`);

    const sceneErrorCount = await page.locator('[data-testid="stage-harness-scene-error"]').count();
    assert.equal(sceneErrorCount, 0, "harness reported a scene/asset load error");

    // VERIFY the video's decoded content in-page before trusting anything
    // downstream (CI runs 29462080026 + 29475319831: failing captures
    // show the clip's FIRST frame under correct overlays, even though the
    // in-app rVFC ready-gate fired — and in run 29475319831 the stale
    // state survived a fresh page load in the same browser, failing both
    // attempts with identical SSIM 0.818982). The fixture is all-intra
    // (90/90 keyframes), so this is not a sparse-GOP seek artifact; the
    // browser session itself can wedge with frame 0 as the presented
    // frame. Strategy: draw the video to an offscreen canvas and compare
    // a downsampled luminance signature against a frame-0 reference
    // signature taken from a second, unseeked video element of the same
    // clip (same in-browser decode pipeline, so "still frame 0" measures
    // ~0 while every case's target frame measures >= 2.23 — see
    // FRAME0_LUMA_DIFF_THRESHOLD calibration). If frame 0 is still the
    // decoded frame, re-seek (0 then t) and re-check up to MAX_RESEEKS
    // times before failing with a distinct, named error.
    if (Number(t) > 0) {
      const check = await page.evaluate(
        async ({ t: target, maxReseeks, threshold }) => {
          const video = document.querySelector('[data-testid="stage-harness-video"]');
          if (!(video instanceof HTMLVideoElement)) {
            return { status: "setup-error", reason: "stage-harness video element not found" };
          }

          const W = 32;
          const H = 18;
          const canvas = document.createElement("canvas");
          canvas.width = W;
          canvas.height = H;
          const g = canvas.getContext("2d", { willReadFrequently: true });
          if (!g) return { status: "setup-error", reason: "2d canvas context unavailable" };
          const signature = (source) => {
            g.drawImage(source, 0, 0, W, H);
            const { data } = g.getImageData(0, 0, W, H);
            const out = new Array(W * H);
            for (let i = 0; i < W * H; i += 1) {
              out[i] = 0.2126 * data[i * 4] + 0.7152 * data[i * 4 + 1] + 0.0722 * data[i * 4 + 2];
            }
            return out;
          };
          const meanAbsDiff = (a, b) => {
            let sum = 0;
            for (let i = 0; i < a.length; i += 1) sum += Math.abs(a[i] - b[i]);
            return sum / a.length;
          };

          // Frame-0 reference: a second video element on the same clip,
          // never seeked, so its decoded frame IS frame 0 — through the
          // exact same decode pipeline as the element under test.
          const ref = document.createElement("video");
          ref.muted = true;
          ref.preload = "auto";
          ref.src = video.currentSrc || video.src;
          try {
            await new Promise((resolve, reject) => {
              const timer = setTimeout(() => reject(new Error("timeout")), 10000);
              ref.addEventListener(
                "loadeddata",
                () => {
                  clearTimeout(timer);
                  resolve();
                },
                { once: true },
              );
              ref.addEventListener(
                "error",
                () => {
                  clearTimeout(timer);
                  reject(new Error("media error"));
                },
                { once: true },
              );
              ref.load();
            });
          } catch (e) {
            return { status: "setup-error", reason: `frame-0 reference video failed to load: ${e.message}` };
          }
          const frame0Sig = signature(ref);

          const seekTo = (time) =>
            new Promise((resolve, reject) => {
              const timer = setTimeout(() => reject(new Error(`re-seek to ${time} timed out`)), 5000);
              video.addEventListener(
                "seeked",
                () => {
                  clearTimeout(timer);
                  resolve();
                },
                { once: true },
              );
              video.currentTime = time;
            });
          const presentedAt = (time) =>
            new Promise((resolve) => {
              if (typeof video.requestVideoFrameCallback !== "function") {
                resolve();
                return;
              }
              const timer = setTimeout(resolve, 2000);
              const onFrame = (_now, metadata) => {
                if (Math.abs(metadata.mediaTime - time) <= 1 / 60) {
                  clearTimeout(timer);
                  resolve();
                  return;
                }
                video.requestVideoFrameCallback(onFrame);
              };
              video.requestVideoFrameCallback(onFrame);
            });

          let diff = meanAbsDiff(signature(video), frame0Sig);
          let reseeks = 0;
          while (diff <= threshold && reseeks < maxReseeks) {
            reseeks += 1;
            try {
              await seekTo(0);
              await seekTo(target);
            } catch (e) {
              return { status: "setup-error", reason: e.message, reseeks };
            }
            await presentedAt(target);
            diff = meanAbsDiff(signature(video), frame0Sig);
          }
          return {
            status: diff > threshold ? "ok" : "stale",
            reseeks,
            diff: Number(diff.toFixed(2)),
          };
        },
        { t: Number(t), maxReseeks: MAX_RESEEKS, threshold: FRAME0_LUMA_DIFF_THRESHOLD },
      );

      if (check.status === "setup-error") {
        throw new Error(`video content check could not run: ${check.reason}`);
      }
      if (check.status === "stale") {
        throw new Error(
          `video never presented seeked frame after ${MAX_RESEEKS} re-seeks ` +
            `(frame-0 luma diff ${check.diff} <= ${FRAME0_LUMA_DIFF_THRESHOLD}, t=${t})`,
        );
      }
      if (check.reseeks > 0) {
        console.error(
          `[stage-harness t=${t}] video content check recovered after ${check.reseeks} re-seek(s) ` +
            `(final frame-0 luma diff ${check.diff})`,
        );
      }
    }

    // What the CI flake actually is (diagnosed from run 29462080026's
    // artifact): the OVERLAYS in a failing capture are pixel-identical
    // to the golden — text, fonts, positions all correct — but the
    // underlying VIDEO shows the clip's FIRST frame (t=0) instead of
    // the seeked frame. SSIM of the failing kinetic-text t=1.5 shot's
    // video region: 0.9987 vs frame 0, 0.7986 vs the correct frame 45.
    // Only two frames are ever presented in the page's life (frame 0 on
    // load, frame N after the seek), so a stale capture is always the
    // same wrong image — which is why failing SSIMs repeat byte-identical
    // across runs (0.818982 twice) instead of varying like a mid-paint
    // race would.
    //
    // Why the in-page rVFC ready-gate doesn't prevent it: rVFC firing
    // with mediaTime == t proves the seeked frame was SUBMITTED for
    // compositing (that's what flips the title), but after that the
    // harness page is completely static — nothing mutates the DOM, and
    // rAF callbacks alone create no compositor damage. On a busy
    // software-rendered CI compositor the captured surface can still
    // hold the pre-seek video quad. So: force REAL damage (a style
    // mutation on the root) to make the compositor produce a fresh
    // display frame that must include the current video quad, then wait
    // two rAFs (rAF fires before paint, so the second one is only
    // reached after the first's frame was generated), revert, and wait
    // again. The transparent outline changes zero pixels but is a
    // genuine style invalidation.
    await page.evaluate(async () => {
      const root = document.querySelector('[data-testid="stage-harness-root"]');
      const twoFrames = () =>
        new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)));
      // Reading layout forces any pending style recalc synchronously.
      void root?.getBoundingClientRect();
      if (root) root.style.outline = "1px solid transparent";
      await twoFrames();
      if (root) root.style.outline = "";
      await twoFrames();
    });

    // Assert the expected overlay DOM landed before trusting the screenshot.
    const frame = page.locator('[data-testid="stage-harness-root"]');
    await frame.waitFor({ state: "visible" });
    await assertDom(page);

    // Screenshot only the program-frame element — avoids window-chrome
    // variance since the frame itself is a fixed 1280x720 box. Capture
    // via Playwright's own screenshot (not a raw CDP call) so it
    // continues to wait for its own actionability/stability checks on
    // top of the paint wait above — belt and suspenders against a
    // mid-paint capture.
    await frame.screenshot({ path: shotPath, animations: "disabled" });
  } finally {
    await page.close();
  }
}

/**
 * Compare a screenshot against its golden. Returns `{ ok, score }`
 * (score is the parsed SSIM, or null if unparseable). Throws only on a
 * broken environment: ssim-compare.sh exits 2 when ffmpeg is missing or
 * failed, and reporting a broken environment as "diverged" is how a
 * gate that never actually compared anything still looks like it ran.
 */
function ssimCompare(shotPath, goldenPath) {
  const script = path.join(REPO_ROOT, "scripts/ssim-compare.sh");
  let output;
  let ok;
  try {
    output = execFileSync(script, [shotPath, goldenPath, MIN_SSIM], { encoding: "utf8" });
    ok = true;
  } catch (err) {
    if (err.status === 2) {
      process.stderr.write(String(err.stderr ?? ""));
      throw new Error("could not compare: ffmpeg is missing or failed (see above)");
    }
    output = `${err.stdout ?? ""}${err.stderr ?? ""}`;
    ok = false;
  }
  process.stdout.write(output);
  const match = /SSIM=([0-9.]+)/.exec(output);
  return { ok, score: match ? match[1] : null };
}

/** Run one case: capture, then bootstrap or golden-compare — with ONE
 * evidence-preserving recapture. The known CI flake is a stale video
 * frame (see the content-check and damage-forcing comments in
 * captureCase); when the first compare fails, the failing screenshot is
 * kept with an `-attempt1` suffix (the CI artifact glob
 * `stage-harness-*.png` uploads it), its SSIM is printed, and the case
 * is re-run in a freshly LAUNCHED browser (the bad state is
 * session-sticky, so a fresh page in the same browser is not enough).
 * Both attempts' SSIMs are always printed so flakes stay visible and
 * countable; a genuine visual regression fails both attempts and the
 * case still fails. */
async function runCase(ctx, testCase) {
  const { name, t } = testCase;
  const caseLabel = `${name} t=${t}`;
  const shotPath = path.join(SCREENSHOT_DIR, `stage-harness-${name}-t${t}.png`);
  const goldenPath = path.join(GOLDEN_DIR, `${name}-t${t}-${process.platform}.png`);

  await captureCase(ctx, testCase, shotPath);

  if (!existsSync(goldenPath)) {
    if (process.env.STAGE_GOLDEN_BOOTSTRAP !== "1") {
      throw new Error(
        `missing committed golden ${goldenPath}; screenshot saved at ${shotPath} — ` +
          `rerun with STAGE_GOLDEN_BOOTSTRAP=1 to seed it, then commit the golden`,
      );
    }
    copyFileSync(shotPath, goldenPath);
    console.log(`[${caseLabel}] golden bootstrapped: ${goldenPath}`);
    return;
  }

  const first = ssimCompare(shotPath, goldenPath);
  if (first.ok) {
    console.log(`[${caseLabel}] screenshot matches golden (>= ${MIN_SSIM})`);
    return;
  }

  const attempt1Path = shotPath.replace(/\.png$/, "-attempt1.png");
  copyFileSync(shotPath, attempt1Path);
  console.error(
    `[${caseLabel}] attempt 1 diverged (SSIM=${first.score ?? "?"} < ${MIN_SSIM}); ` +
      `evidence kept at ${attempt1Path}; recapturing once from a fresh browser launch`,
  );

  // Fresh browser PROCESS, not just a fresh page: run 29475319831 showed
  // the stale-video state is session-sticky — a fresh page load in the
  // same browser reproduced the byte-identical stale capture.
  const retryBrowser = await chromium.launch();
  let second;
  try {
    const retryCtx = await retryBrowser.newContext(CONTEXT_OPTIONS);
    await captureCase(retryCtx, testCase, shotPath);
    second = ssimCompare(shotPath, goldenPath);
  } finally {
    await retryBrowser.close();
  }
  console.error(
    `[${caseLabel}] attempt SSIMs: 1=${first.score ?? "?"} 2=${second.score ?? "?"} (min ${MIN_SSIM})`,
  );
  if (!second.ok) {
    throw new Error(
      `screenshot diverged from golden below ${MIN_SSIM} on both attempts ` +
        `(SSIM ${first.score ?? "?"} then ${second.score ?? "?"}): ${goldenPath}`,
    );
  }
  console.log(`[${caseLabel}] screenshot matches golden on attempt 2 (>= ${MIN_SSIM}) — attempt 1 was a stale-frame flake`);
}

await ensureAppServer();

const browser = await chromium.launch();
const ctx = await browser.newContext(CONTEXT_OPTIONS);

let failures = 0;

try {
  for (const testCase of CASES) {
    const caseLabel = `${testCase.name} t=${testCase.t}`;
    try {
      await runCase(ctx, testCase);
    } catch (err) {
      console.error(`FAIL stage-harness [${caseLabel}]: ${err.message}`);
      failures += 1;
    }
  }
} finally {
  await browser.close();
  await stopAppServer();
}

if (failures > 0) {
  console.error(`stage-harness: ${failures}/${CASES.length} case(s) failed`);
  process.exit(1);
}
console.log(`stage-harness: all ${CASES.length} cases passed`);
process.exit(0);
