#!/usr/bin/env node
/**
 * Stage harness screenshot gate (Phase-1 Task 8, parameterized over
 * template scenes in Phase-2 Task 7).
 *
 * Boots (or reuses) the desktop dev server, then for each case in
 * CASES loads the deterministic `/stage-harness` route at a frozen
 * clock time, waits for `document.title === "stage-harness-ready"`,
 * DOM-asserts the expected overlays landed, screenshots just the
 * program-frame element, and compares it against a committed
 * per-platform golden via ffmpeg SSIM (see `scripts/ssim-compare.sh`).
 *
 * A missing per-platform golden is a hard failure so the gate can never
 * silently self-seed in CI. To seed a new platform, run once locally with
 * STAGE_GOLDEN_BOOTSTRAP=1 (or commit the screenshot CI uploads as the
 * `stage-harness-screenshots` artifact) and commit the golden.
 *
 * Template scene fixtures (`scene-lower-third.json`,
 * `scene-kinetic-text.json`) are generated by the sync tests in
 * `crates/core/tests/motion_template_goldens.rs` from
 * `expand_template` + the snapshot lowering's field mapping — do not
 * hand-edit them; regenerate with UPDATE_GOLDENS=1 there. Two
 * timestamps per template catch mid-animation states (slide-in in
 * flight vs settled; words mid-pop vs held).
 *
 * Follows the dev-server boot/reuse pattern of `tests/desktop-ui-smoke.mjs`
 * (canReachApp / ensureAppServer / stopAppServer), spawning
 * `pnpm --dir apps/desktop exec vite` when the app isn't already up.
 */

import { chromium } from "playwright";
import { strict as assert } from "node:assert";
import { spawn, execFileSync } from "node:child_process";
import { mkdirSync, existsSync, copyFileSync } from "node:fs";
import { setTimeout as delay } from "node:timers/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = fileURLToPath(new URL("../../..", import.meta.url));
const BASE_URL = process.env.SMOKE_URL ?? "http://127.0.0.1:1420/";
const APP_URL = new URL(BASE_URL);
const APP_PORT = APP_URL.port || (APP_URL.protocol === "https:" ? "443" : "80");
const SCREENSHOT_DIR = process.env.SMOKE_OUT_DIR ?? "tests/smoke";
const GOLDEN_DIR = "tests/fixtures/stage-golden";
mkdirSync(SCREENSHOT_DIR, { recursive: true });
mkdirSync(GOLDEN_DIR, { recursive: true });

const MIN_SSIM = "0.98";

const MOTION_TITLE_SELECTOR = ".timeline-motion-scene-layer .timeline-title-overlay";
const LEGACY_TITLE_SELECTOR = ".timeline-title-layer .timeline-title-overlay";
const SHAPE_SELECTOR = ".timeline-motion-shape-rect";
const IMAGE_SELECTOR = ".timeline-motion-image";

async function overlayTexts(page, selector) {
  const layer = page.locator(selector);
  const count = await layer.count();
  const texts = [];
  for (let index = 0; index < count; index += 1) {
    texts.push((await layer.nth(index).textContent()) ?? "");
  }
  return texts;
}

async function assertOverlayCounts(page, { legacyTitles, motionTitles, shapes, images }) {
  assert.equal(
    await page.locator(LEGACY_TITLE_SELECTOR).count(),
    legacyTitles,
    `expected ${legacyTitles} legacy title overlay(s)`,
  );
  assert.equal(
    await page.locator(MOTION_TITLE_SELECTOR).count(),
    motionTitles,
    `expected ${motionTitles} motion-scene title overlay(s)`,
  );
  assert.equal(
    await page.locator(SHAPE_SELECTOR).count(),
    shapes,
    `expected ${shapes} shape overlay(s)`,
  );
  assert.equal(
    await page.locator(IMAGE_SELECTOR).count(),
    images,
    `expected ${images} image overlay(s)`,
  );
}

/** Phase-1 scene: one legacy title + one rect + one image. */
async function assertSceneBasic(page) {
  await assertOverlayCounts(page, { legacyTitles: 1, motionTitles: 0, shapes: 1, images: 1 });
  const [titleText] = await overlayTexts(page, LEGACY_TITLE_SELECTOR);
  assert.ok(titleText.includes("STAGE HARNESS"), `title overlay text mismatch: ${titleText}`);
}

/** Lower third: accent bar + name + role, at both timestamps (the bar
 * slides but never leaves its 0..5s window; both texts are staggered
 * in by 0.16s, so all three overlays exist at t=0.4 and t=2.0). */
async function assertLowerThird(page) {
  await assertOverlayCounts(page, { legacyTitles: 0, motionTitles: 2, shapes: 1, images: 0 });
  const texts = await overlayTexts(page, MOTION_TITLE_SELECTOR);
  assert.deepEqual(texts, ["Ada Lovelace", "Mathematician"], "lower-third text overlays mismatch");
}

/** Kinetic text: word layers have their own windows, so the visible
 * word set is timestamp-specific. */
function assertKineticWords(expectedWords) {
  return async (page) => {
    await assertOverlayCounts(page, {
      legacyTitles: 0,
      motionTitles: expectedWords.length,
      shapes: 0,
      images: 0,
    });
    const texts = await overlayTexts(page, MOTION_TITLE_SELECTOR);
    assert.deepEqual(texts, expectedWords, "kinetic-text word overlays mismatch");
  };
}

/**
 * Case table. `name` + `t` name the screenshot and per-platform golden
 * (`<name>-t<t>-<platform>.png`); `assertDom` pins the expected overlay
 * DOM before the screenshot is trusted.
 */
const CASES = [
  {
    name: "scene-basic",
    scene: "/fixtures/stage/scene-basic.json",
    t: "1.0",
    assertDom: assertSceneBasic,
  },
  {
    // Slide-in mid-flight: bar/name/role all inside their 0.55s
    // ease-out-cubic slide (and the texts mid fade-in).
    name: "scene-lower-third",
    scene: "/fixtures/stage/scene-lower-third.json",
    t: "0.4",
    assertDom: assertLowerThird,
  },
  {
    // Settled: slides and fades done, holding at final x / peak opacity.
    name: "scene-lower-third",
    scene: "/fixtures/stage/scene-lower-third.json",
    t: "2.0",
    assertDom: assertLowerThird,
  },
  {
    // "Ship" mid-exit-fade, "it" mid pop-in (opacity+spring scale),
    // "today" not yet started.
    name: "scene-kinetic-text",
    scene: "/fixtures/stage/scene-kinetic-text.json",
    t: "0.5",
    assertDom: assertKineticWords(["Ship", "it"]),
  },
  {
    // Earlier words exited; only "today" remains, settled.
    name: "scene-kinetic-text",
    scene: "/fixtures/stage/scene-kinetic-text.json",
    t: "1.5",
    assertDom: assertKineticWords(["today"]),
  },
];

let appServer = null;

async function canReachApp() {
  try {
    const response = await fetch(BASE_URL, { signal: AbortSignal.timeout(500) });
    return response.ok;
  } catch {
    return false;
  }
}

async function ensureAppServer() {
  if (await canReachApp()) return;

  appServer = spawn("pnpm", ["--dir", "apps/desktop", "exec", "vite", "--host", "127.0.0.1", "--port", APP_PORT, "--strictPort"], {
    cwd: REPO_ROOT,
    env: { ...process.env, BROWSER: "none", VITE_MONTAGE_SKIP_WELCOME: "1" },
    detached: process.platform !== "win32",
    stdio: ["ignore", "pipe", "pipe"],
  });

  appServer.stdout.on("data", (chunk) => process.stdout.write(chunk));
  appServer.stderr.on("data", (chunk) => process.stderr.write(chunk));

  for (let attempt = 0; attempt < 60; attempt += 1) {
    if (await canReachApp()) return;
    if (appServer.exitCode !== null) {
      throw new Error(`dev server exited before ${BASE_URL} became reachable`);
    }
    await delay(500);
  }

  throw new Error(`timed out waiting for ${BASE_URL}`);
}

async function stopAppServer() {
  if (appServer && appServer.exitCode === null) {
    const stopped = new Promise((resolve) => {
      appServer.once("exit", resolve);
    });
    if (process.platform === "win32") {
      appServer.kill("SIGTERM");
    } else {
      process.kill(-appServer.pid, "SIGTERM");
    }
    await Promise.race([stopped, delay(2000)]);
  }
}

process.on("SIGINT", () => {
  stopAppServer();
  process.exit(130);
});
process.on("SIGTERM", () => {
  stopAppServer();
  process.exit(143);
});

/** Run one case: navigate, DOM-assert, screenshot, bootstrap/compare. */
async function runCase(ctx, testCase) {
  const { name, scene, t, assertDom } = testCase;
  const caseLabel = `${name} t=${t}`;
  const harnessUrl = new URL(`/stage-harness?t=${t}&scene=${scene}`, BASE_URL).toString();
  const shotPath = path.join(SCREENSHOT_DIR, `stage-harness-${name}-t${t}.png`);
  const goldenPath = path.join(GOLDEN_DIR, `${name}-t${t}-${process.platform}.png`);

  const page = await ctx.newPage();
  try {
    const errors = [];
    page.on("pageerror", (e) => errors.push(`pageerror: ${e.message}`));
    page.on("console", (m) => {
      if (m.type() === "error") errors.push(`console.error: ${m.text()}`);
    });

    await page.goto(harnessUrl, { waitUntil: "networkidle" });
    await page.waitForFunction(() => document.title === "stage-harness-ready", null, { timeout: 15000 });

    assert.deepEqual(errors, [], `harness console/page errors: ${errors.join("; ")}`);

    const sceneErrorCount = await page.locator('[data-testid="stage-harness-scene-error"]').count();
    assert.equal(sceneErrorCount, 0, "harness reported a scene/asset load error");

    // `stage-harness-ready` means the seeked frame has been PRESENTED
    // (requestVideoFrameCallback), but presented is not painted: the
    // compositor still has to draw it. Screenshotting in that window
    // captures the pre-seek frame — which is what made kinetic-text
    // diverge on the Linux runner while the same run's other cases
    // passed. Its spring-animated word layers give the compositor more
    // to do, widening the gap.
    //
    // Wait for two animation frames: rAF fires before paint, so the
    // second one is only reached after the first has been painted.
    await page.evaluate(
      () => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))),
    );

    // Assert the expected overlay DOM landed before trusting the screenshot.
    const frame = page.locator('[data-testid="stage-harness-root"]');
    await frame.waitFor({ state: "visible" });
    await assertDom(page);

    // Screenshot only the program-frame element — avoids window-chrome
    // variance since the frame itself is a fixed 1280x720 box.
    await frame.screenshot({ path: shotPath });
  } finally {
    await page.close();
  }

  if (!existsSync(goldenPath)) {
    if (process.env.STAGE_GOLDEN_BOOTSTRAP !== "1") {
      throw new Error(
        `missing committed golden ${goldenPath}; screenshot saved at ${shotPath} — ` +
          `rerun with STAGE_GOLDEN_BOOTSTRAP=1 to seed it, then commit the golden`,
      );
    }
    copyFileSync(shotPath, goldenPath);
    console.log(`[${caseLabel}] golden bootstrapped: ${goldenPath}`);
    return;
  }
  try {
    execFileSync(
      path.join(REPO_ROOT, "scripts/ssim-compare.sh"),
      [shotPath, goldenPath, MIN_SSIM],
      { stdio: "inherit" },
    );
    console.log(`[${caseLabel}] screenshot matches golden (>= ${MIN_SSIM})`);
  } catch (err) {
    // ssim-compare.sh exits 2 when ffmpeg is missing and 1 on a real
    // divergence. Reporting a broken environment as "diverged" is how a
    // gate that never actually compared anything still looks like it ran.
    if (err.status === 2) {
      throw new Error("could not compare: ffmpeg is missing (see above)");
    }
    throw new Error(`screenshot diverged from golden below ${MIN_SSIM}: ${goldenPath}`);
  }
}

await ensureAppServer();

const browser = await chromium.launch();
const ctx = await browser.newContext({
  viewport: { width: 1280, height: 720 },
  deviceScaleFactor: 1,
});

let failures = 0;

try {
  for (const testCase of CASES) {
    const caseLabel = `${testCase.name} t=${testCase.t}`;
    try {
      await runCase(ctx, testCase);
    } catch (err) {
      console.error(`FAIL stage-harness [${caseLabel}]: ${err.message}`);
      failures += 1;
    }
  }
} finally {
  await browser.close();
  await stopAppServer();
}

if (failures > 0) {
  console.error(`stage-harness: ${failures}/${CASES.length} case(s) failed`);
  process.exit(1);
}
console.log(`stage-harness: all ${CASES.length} cases passed`);
process.exit(0);
