[package]
name = "awidat-secrets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "awidat_secrets"
path = "src/lib.rs"

[dependencies]
keyring = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
