-- Phase 1: enable pg_cron and pg_net extensions.
--
-- Supabase scopes pg_cron to the `postgres` database and requires enabling it
-- at the project level via the dashboard (Extensions tab) or:
--   ALTER DATABASE postgres WITH pg_cron;
-- before this migration can run.  pg_net is typically pre-enabled on Supabase
-- managed projects but is listed here for completeness.
--
-- These CREATE EXTENSION statements are safe to apply multiple times (IF NOT EXISTS).

CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

-- Phase 1 cron registration: DISABLED PLACEHOLDER.
--
-- The schedule below is intentionally commented out.  Enabling a live cron
-- before the real provider adapters exist (Phase 3) and the minute-tick logic
-- is hardened (Phase 4) would fire no-ops into the service every minute.
-- Phase 4 uncomments and activates this once Phases 2 and 3 are merged.
--
-- To activate in Phase 4, run in the Supabase SQL editor:
--   SELECT cron.schedule(
--       'awidat-publish-tick',
--       '* * * * *',
--       $$
--         SELECT net.http_post(
--             url     := 'https://<app>.fly.dev/internal/tick',
--             headers := jsonb_build_object(
--                            'Content-Type',  'application/json',
--                            'Authorization', 'Bearer <SERVICE_SHARED_SECRET>'
--                        ),
--             body    := '{}'::jsonb
--         );
--       $$
--   );
--
-- Smoke-test (Step 8, run once manually after deployment):
--   SELECT net.http_post(
--       url     := 'https://<app>.fly.dev/internal/tick',
--       headers := jsonb_build_object(
--                      'Content-Type',  'application/json',
--                      'Authorization', 'Bearer <SERVICE_SHARED_SECRET>'
--                  ),
--       body    := '{}'::jsonb
--   );
--   -- Then confirm: SELECT * FROM net._http_response ORDER BY created DESC LIMIT 5;
