import React, { useState } from "react";
import ReactDOM from "react-dom/client";
import "./ui/tokens.css";
import "./ui/glass.css";
import {
  AmbientBackground,
  GlassPanel,
  GlassContent,
  GlassButton,
  useCursorGlass,
} from "./ui/glass";

/* ------------------------------------------------------------------ */
/*  Awidat "Obsidian Glass" 2026 — showcase                            */
/*  Browser-openable (no Tauri). Three scenes flip via the top switch. */
/* ------------------------------------------------------------------ */

function Mark({ size = 64 }: { size?: number }) {
  return (
    <div
      className="relative grid place-items-center rounded-2xl"
      style={{
        width: size,
        height: size,
        background: "linear-gradient(160deg, #1b1b1f, #0e0e11)",
        border: "1px solid rgba(255,255,255,0.10)",
        boxShadow:
          "0 0 0 1px rgba(255,122,24,0.25), 0 8px 30px rgba(255,122,24,0.30), inset 0 1px 0 rgba(255,255,255,0.12)",
      }}
    >
      <svg width={size * 0.5} height={size * 0.5} viewBox="0 0 24 24" aria-hidden>
        <defs>
          <linearGradient id="tri" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0" stopColor="#FFB040" />
            <stop offset="1" stopColor="#FF7A18" />
          </linearGradient>
        </defs>
        <path d="M12 3 L21 20 L3 20 Z" fill="url(#tri)" />
      </svg>
    </div>
  );
}

/* ============================ SCENE 1: LANDING ============================ */
function LandingScene() {
  return (
    <div className="relative z-10 flex h-full w-full flex-col items-center justify-center px-6 text-center">
      <div style={{ filter: "drop-shadow(0 0 40px rgba(255,122,24,0.35))" }}>
        <Mark size={76} />
      </div>
      <div className="mt-4 font-mono text-[13px] tracking-[0.34em] text-[var(--color-text-secondary)]">
        A W I D A T
      </div>
      <h1 className="mt-6 max-w-[22ch] text-[30px] font-bold leading-tight text-[var(--color-text-primary)]">
        The editor that{" "}
        <span style={{ color: "#FF9A45" }}>reads your footage</span> and proposes
        the cut.
      </h1>
      <p className="mt-3 max-w-[44ch] text-[13px] leading-relaxed text-[var(--color-text-muted)]">
        Drop a file. Awidat indexes the transcript, scenes, speakers and silences,
        then suggests editorial cuts with a reason for each — you accept, reject,
        or refine inline.
      </p>

      <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
        <GlassButton variant="cta" kbd="⌘N">＋ New project</GlassButton>
        <GlassButton kbd="⌘I">Import media</GlassButton>
        <GlassButton kbd="⌘O">Open…</GlassButton>
      </div>

      {/* recents as floating glass chips */}
      <div className="mt-10 flex items-center gap-2 text-[11px] text-[var(--color-text-muted)]">
        <span className="font-mono uppercase tracking-wider">recent</span>
        {["new_cast", "ep_14_interview", "launch_promo"].map((r) => (
          <button
            key={r}
            className="glass-ghost rounded-lg px-2.5 py-1 font-mono text-[11px]"
          >
            {r}
          </button>
        ))}
      </div>

      {/* three-idea strip floating on glass */}
      <GlassPanel
        elevation="soft"
        radius={20}
        className="mt-12 grid max-w-[680px] grid-cols-3 gap-px overflow-hidden"
        style={{ background: "rgba(255,255,255,0.03)" }}
      >
        {[
          { t: "Reads", d: "9 signals indexed locally — transcript to silences." },
          { t: "Proposes", d: "Editorial cuts, B-roll, color — each with a rationale." },
          { t: "Learns", d: "Reject with a reason; the agent stops repeating it." },
        ].map((c, i) => (
          <div key={c.t} className="px-5 py-4 text-left" style={{ background: "rgba(14,14,17,0.5)" }}>
            <div className="font-mono text-[10px] text-[#FF9A45]">0{i + 1}</div>
            <div className="mt-1 text-[13px] font-semibold text-[var(--color-text-primary)]">
              {c.t}
            </div>
            <div className="mt-1 text-[11px] leading-snug text-[var(--color-text-muted)]">
              {c.d}
            </div>
          </div>
        ))}
      </GlassPanel>
    </div>
  );
}

/* ============================ SCENE 2: EDITOR ============================ */

const MEDIUM_COLOR: Record<string, string> = {
  cut: "#67E8F9",
  broll: "#D8B4FE",
  color: "#FCD34D",
};

const PROPOSALS = [
  {
    id: "p1",
    medium: "cut",
    title: "Trim 0:12 — 0:12.42",
    rationale: "Silence > 300ms exceeded the podcast-cleanup threshold from AGENTS.md.",
  },
  {
    id: "p2",
    medium: "cut",
    title: "Cut filler 0:24 — 0:31.8",
    rationale: 'Transcript flagged "um, like…" — 7s of filler removed.',
  },
  {
    id: "p3",
    medium: "broll",
    title: "B-roll 0:14 — 0:18",
    rationale: "Generated by replicate/sd-3 from 'sunset over coastline' — disclosure auto-added.",
  },
  {
    id: "p4",
    medium: "color",
    title: "Warm grade · scene 3",
    rationale: "Shadows at 3200K read cold against the 5600K key — nudged +400K.",
  },
];

function ProposalCard({ p }: { p: (typeof PROPOSALS)[number] }) {
  const { ref, onMouseMove } = useCursorGlass<HTMLDivElement>();
  const color = MEDIUM_COLOR[p.medium];
  return (
    <div
      ref={ref}
      onMouseMove={onMouseMove}
      className="glass glass-reactive relative overflow-hidden p-3"
      style={{ borderRadius: 14 }}
    >
      <div className="flex items-start gap-2">
        <span
          className="mt-0.5 rounded-md px-1.5 py-0.5 font-mono text-[9px] uppercase tracking-wide"
          style={{ color, background: `${color}1f`, border: `1px solid ${color}3a` }}
        >
          {p.medium}
        </span>
        <div className="min-w-0 flex-1">
          <div className="truncate text-[13px] font-semibold text-[var(--color-text-primary)]">
            {p.title}
          </div>
          <div className="mt-0.5 text-[11px] italic leading-snug text-[var(--color-text-muted)]">
            {p.rationale}
          </div>
        </div>
      </div>
      <div className="mt-3 flex items-center gap-2">
        <GlassButton variant="cta" className="h-7 px-3 text-[11px]">
          Accept
        </GlassButton>
        <GlassButton className="h-7 px-3 text-[11px]">Reject</GlassButton>
        <button
          className="ml-auto text-[11px] font-medium"
          style={{ color }}
        >
          Review →
        </button>
      </div>
    </div>
  );
}

function FrostedChrome() {
  return (
    <GlassPanel
      elevation="strong"
      radius={0}
      className="flex items-center gap-4 px-4"
      style={{ height: 52, borderLeft: "none", borderRight: "none", borderTop: "none" }}
    >
      <div className="flex items-center gap-2">
        <Mark size={26} />
        <span className="font-mono text-[12px] tracking-[0.22em] text-[var(--color-text-secondary)]">
          AWIDAT
        </span>
      </div>
      <div
        className="glass-ghost flex items-center gap-2 rounded-lg px-2.5 py-1 font-mono text-[11px]"
        style={{ color: "var(--color-text-muted)" }}
      >
        <span className="text-[var(--color-text-secondary)]">new_cast</span>
        <span className="opacity-50">/Users/explicit/Downloads/new_cast</span>
      </div>
      <nav className="ml-2 flex items-center gap-1 text-[12px]">
        {["Edit", "Deliver", "Skills", "History"].map((t, i) => (
          <button
            key={t}
            className="relative rounded-lg px-3 py-1.5 transition"
            style={{
              color: i === 0 ? "var(--color-text-primary)" : "var(--color-text-muted)",
              background: i === 0 ? "rgba(255,255,255,0.06)" : "transparent",
            }}
          >
            {t}
            {i === 0 && (
              <span
                className="absolute inset-x-2 -bottom-px h-0.5 rounded-full"
                style={{ background: "#FF7A18", boxShadow: "0 0 8px #FF7A18" }}
              />
            )}
          </button>
        ))}
      </nav>
      <div className="ml-auto flex items-center gap-3">
        <div className="glass-ghost flex items-center gap-1.5 rounded-full px-1 py-1 text-[11px]">
          <span className="rounded-full bg-[rgba(255,122,24,0.18)] px-2.5 py-0.5 font-semibold text-[#FF9A45]">
            Pro
          </span>
          <span className="px-2 text-[var(--color-text-muted)]">Creator</span>
        </div>
        <span className="font-mono text-[11px] text-[var(--color-text-muted)]">
          00:06:35:21
        </span>
      </div>
    </GlassPanel>
  );
}

function EditorScene() {
  return (
    <div className="relative z-10 flex h-full flex-col">
      <FrostedChrome />
      <div className="flex min-h-0 flex-1 gap-3 p-3">
        {/* LEFT: agent rail */}
        <GlassPanel reactive className="flex w-[300px] flex-col p-3">
          <div className="flex items-center gap-2 px-1 pb-3">
            <span className="h-1.5 w-1.5 rounded-full bg-[#20C997] shadow-[0_0_8px_#20C997]" />
            <span className="text-[12px] font-semibold text-[var(--color-text-primary)]">
              Agent
            </span>
            <span className="ml-auto font-mono text-[10px] text-[var(--color-text-muted)]">
              gpt · ready
            </span>
          </div>
          <GlassContent className="p-3 text-[12px] leading-relaxed text-[var(--color-text-secondary)]">
            I read your <span className="text-[#FF9A45]">AGENTS.md</span> — podcast,
            ≤ 12 min, trim filler. Indexed 9 signals on Demo (Raw).mp4: 4 scenes,
            2 speakers, 11 silences. Say the word and I'll prepare a starting cut.
          </GlassContent>
          <div className="mt-3 flex flex-col gap-1.5">
            {["Prepare a starting cut", "Tighten to 10 minutes", "Find the best pull-quote"].map(
              (s) => (
                <button
                  key={s}
                  className="glass-ghost rounded-lg px-3 py-2 text-left text-[12px]"
                >
                  {s}
                </button>
              ),
            )}
          </div>
          <div className="mt-auto pt-3">
            <div className="glass-content flex items-center gap-2 px-3 py-2">
              <span className="text-[12px] text-[var(--color-text-muted)]">
                Ask, edit, trim, propose…
              </span>
              <GlassButton variant="cta" className="ml-auto h-7 px-3 text-[11px]">
                Send
              </GlassButton>
            </div>
          </div>
        </GlassPanel>

        {/* CENTER: the Brief */}
        <div className="flex min-w-0 flex-1 flex-col gap-3">
          <GlassPanel className="flex items-center gap-1 px-2 py-1.5" radius={14}>
            {["Brief", "Source", "Timeline"].map((t, i) => (
              <button
                key={t}
                className="rounded-lg px-3 py-1.5 text-[12px] font-medium transition"
                style={{
                  color: i === 0 ? "#1A0E04" : "var(--color-text-muted)",
                  background: i === 0 ? "linear-gradient(180deg,#FF8B33,#FF7A18)" : "transparent",
                }}
              >
                {t}
                {i === 0 && (
                  <span className="ml-1.5 rounded bg-[rgba(26,14,4,0.25)] px-1 font-mono text-[9px]">
                    4
                  </span>
                )}
              </button>
            ))}
          </GlassPanel>

          <GlassPanel className="flex min-h-0 flex-1 flex-col p-4" radius={18}>
            <div className="flex items-baseline justify-between pb-3">
              <h2 className="text-[15px] font-bold text-[var(--color-text-primary)]">
                4 proposals waiting
              </h2>
              <GlassButton variant="cta" className="h-7 px-3 text-[11px]">
                Accept all
              </GlassButton>
            </div>
            <div className="flex min-h-0 flex-1 flex-col gap-2.5 overflow-auto pr-1">
              {PROPOSALS.map((p) => (
                <ProposalCard key={p.id} p={p} />
              ))}
            </div>
            {/* evidence chip row */}
            <div className="mt-3 flex flex-wrap gap-1.5 border-t border-[var(--glass-border)] pt-3">
              {[
                ["Scenes", "4"],
                ["Speakers", "2"],
                ["Silences", "11"],
                ["Transcript", "38 seg"],
                ["Episodes", "3"],
              ].map(([k, v]) => (
                <span
                  key={k}
                  className="glass-ghost rounded-lg px-2 py-1 font-mono text-[10px]"
                >
                  {k} <span className="text-[var(--color-text-secondary)]">{v}</span>
                </span>
              ))}
            </div>
          </GlassPanel>
        </div>

        {/* RIGHT: inspector */}
        <GlassPanel reactive className="flex w-[280px] flex-col p-3">
          <div className="flex items-center gap-2 px-1 pb-3 text-[12px] font-semibold text-[var(--color-text-primary)]">
            Inspector
            <span className="ml-auto font-mono text-[10px] text-[var(--color-text-muted)]">
              Cut 07
            </span>
          </div>
          <GlassContent glow="cyan" className="p-3">
            <div className="text-[12px] font-semibold text-[var(--color-text-primary)]">
              J-cut · audio leads
            </div>
            <div className="mt-2 grid grid-cols-2 gap-2 font-mono text-[10px] text-[var(--color-text-muted)]">
              <div>in 06:35:21</div>
              <div>out 06:42:05</div>
              <div>conf 0.86</div>
              <div>risk low</div>
            </div>
          </GlassContent>
          <div className="mt-3 space-y-3">
            {[
              ["Exposure", 62, "#FF9A45"],
              ["Contrast", 48, "#67E8F9"],
              ["Saturation", 55, "#D8B4FE"],
            ].map(([label, val, c]) => (
              <div key={label as string}>
                <div className="mb-1 flex justify-between text-[10px] text-[var(--color-text-muted)]">
                  <span>{label}</span>
                  <span className="font-mono">{val}</span>
                </div>
                <div className="h-1 rounded-full bg-[rgba(255,255,255,0.06)]">
                  <div
                    className="h-full rounded-full"
                    style={{
                      width: `${val}%`,
                      background: c as string,
                      boxShadow: `0 0 8px ${c}`,
                    }}
                  />
                </div>
              </div>
            ))}
          </div>
        </GlassPanel>
      </div>
    </div>
  );
}

/* ============================ SCENE 3: COMPONENTS ============================ */
function ComponentsScene() {
  return (
    <div className="relative z-10 mx-auto flex h-full w-full max-w-[900px] flex-col gap-5 overflow-auto p-8">
      <h2 className="text-[18px] font-bold text-[var(--color-text-primary)]">
        Glass primitives
      </h2>

      <section className="flex flex-wrap items-center gap-3">
        <GlassButton variant="cta" kbd="⌘↵">Primary CTA</GlassButton>
        <GlassButton kbd="⌘I">Ghost glass</GlassButton>
        <GlassButton disabled>Disabled</GlassButton>
      </section>

      <section className="grid grid-cols-3 gap-3">
        <GlassPanel reactive className="p-4" radius={16}>
          <div className="text-[12px] font-semibold text-[var(--color-text-primary)]">
            Reactive panel
          </div>
          <div className="mt-1 text-[11px] text-[var(--color-text-muted)]">
            Move your cursor across me — the sheen follows.
          </div>
        </GlassPanel>
        <GlassPanel elevation="strong" className="p-4" radius={16}>
          <div className="text-[12px] font-semibold text-[var(--color-text-primary)]">
            Strong glass
          </div>
          <div className="mt-1 text-[11px] text-[var(--color-text-muted)]">
            30px blur — for modals + lifted surfaces.
          </div>
        </GlassPanel>
        <GlassPanel elevation="soft" className="p-4" radius={16}>
          <div className="text-[12px] font-semibold text-[var(--color-text-primary)]">
            Soft glass
          </div>
          <div className="mt-1 text-[11px] text-[var(--color-text-muted)]">
            12px — faint overlays + scrims.
          </div>
        </GlassPanel>
      </section>

      <section className="grid grid-cols-3 gap-3">
        {(["brand", "cyan", "violet"] as const).map((g) => (
          <GlassContent key={g} glow={g} className="p-4">
            <div className="text-[12px] font-semibold capitalize text-[var(--color-text-primary)]">
              {g} glow
            </div>
            <div className="mt-1 text-[11px] text-[var(--color-text-muted)]">
              Content card with {g} edge light.
            </div>
          </GlassContent>
        ))}
      </section>
    </div>
  );
}

/* ============================ SHELL + SCENE SWITCH ============================ */
const SCENES = [
  { id: "landing", label: "Landing", el: <LandingScene /> },
  { id: "editor", label: "Editor", el: <EditorScene /> },
  { id: "components", label: "Components", el: <ComponentsScene /> },
] as const;

function Showcase() {
  const [scene, setScene] = useState<(typeof SCENES)[number]["id"]>("landing");
  const active = SCENES.find((s) => s.id === scene)!;
  return (
    <div className="relative h-screen w-screen overflow-hidden font-sans text-[var(--color-text-primary)]">
      <AmbientBackground />
      {active.el}
      {/* floating scene switcher */}
      <GlassPanel
        elevation="strong"
        radius={999}
        className="fixed bottom-5 left-1/2 z-50 flex -translate-x-1/2 items-center gap-1 px-1.5 py-1.5"
      >
        {SCENES.map((s) => (
          <button
            key={s.id}
            onClick={() => setScene(s.id)}
            className="rounded-full px-4 py-1.5 text-[12px] font-medium transition"
            style={{
              color: scene === s.id ? "#1A0E04" : "var(--color-text-secondary)",
              background:
                scene === s.id ? "linear-gradient(180deg,#FF8B33,#FF7A18)" : "transparent",
            }}
          >
            {s.label}
          </button>
        ))}
      </GlassPanel>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <Showcase />
  </React.StrictMode>,
);
