//! Per-project editorial-note persistence.
//!
//! Notes the agent surfaces (dead air, filler words, false starts,
//! continuity warnings, b-roll suggestions) live in
//! `<project>/.awidat/notes.json`. The frontend's NotesPanel reads
//! the file on project load + writes back when the user clicks
//! Dismiss / Resolve. Notes persist across sessions so the user
//! can pick up where they left off.
//!
//! Distinct from the dismissal-pattern memory (`dismissal.rs`):
//! - dismissal memory is *coarse* — "I don't care about
//!   short-silence findings on this project, ever";
//! - notes are *individual* findings the agent surfaced — "the
//!   2.4s silence at 3:14 in raw/ep.mp4."
//!
//! Dismissing one note also stamps the matching coarse pattern
//! into `dismissed_patterns.json` (via the Tauri command path) so
//! the agent doesn't re-surface the same kind on next scan. That
//! coupling lives at the desktop layer; core just owns the load /
//! save shape.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// Filename inside `.awidat/`.
pub const NOTES_FILE: &str = "notes.json";

/// One persisted editorial note. Mirrors the protocol's
/// `Item::EditorialNote` shape minus the wire-only `phase` field.
/// String enums on the wire (kind / status) so the desktop crate
/// can deserialize directly into the protocol types.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PersistedNote {
    /// Stable id — generated by the tool that emitted this note.
    pub id: String,
    /// Editorial kind, serialized as the snake-case string the
    /// protocol's `EditorialNoteKind` uses.
    pub kind: String,
    /// Lifecycle status, serialized as snake-case string.
    pub status: String,
    /// Master-timeline seconds where the finding centers.
    pub anchor_at_s: f64,
    /// One-line summary the panel renders.
    pub summary: String,
    /// Optional EDL text for the note's "Generate Proposal" button.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub suggested_proposal: Option<String>,
    /// Continuity verdict for `continuity_warning` notes. One of
    /// `"clean"` / `"risky"` / `"dirty"` / `"abstain"`. `None` for
    /// other kinds. Phase 2.5.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub continuity_verdict: Option<String>,
    /// Per-rule reasons (only non-clean rules surface here). `None`
    /// for non-continuity kinds. Phase 2.5.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub continuity_reasons: Option<Vec<String>>,
    /// For `broll_suggestion` notes: the Pexels search query the
    /// agent generated. Used by the BrollNoteCard's "Search Pexels"
    /// affordance. `None` for non-broll kinds. Phase 3.4.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub broll_query: Option<String>,
    /// For `broll_suggestion` notes: pre-fetched preview thumbnails
    /// (when the agent has already called `search_broll`). Each
    /// preview is `{ pexels_id, thumbnail_url, duration_s,
    /// attribution, pexels_page }`. `None` for non-broll kinds.
    /// Phase 3.4.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub broll_previews: Option<Vec<serde_json::Value>>,
    /// For `broll_suggestion` notes: exact anchor the desktop should
    /// hand to `use_broll`, e.g. `{ "kind": "clip_uuid", "uuid": "clip-3" }`
    /// or `{ "kind": "transcript_snippet", "text": "..." }`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub broll_anchor: Option<serde_json::Value>,
    /// Optional author tag attached to the finding. Kept optional to keep
    /// old notes backward-compatible and to allow machine-generated notes.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub author: Option<String>,
    /// Optional review comment body for authored notes. Kept optional to keep
    /// old notes backward-compatible.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub comment_text: Option<String>,
}

/// On-disk shape: versioned wrapper so future schema growth
/// (per-asset notes, dependency links between notes, etc) can
/// land without breaking v1 files.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct NotesFile {
    /// Schema version. Currently `1`.
    pub version: u32,
    /// All notes, in arrival order. The panel sorts by status
    /// (open first) and anchor_at_s — order on disk is a stable
    /// audit trail, not a render order.
    pub notes: Vec<PersistedNote>,
}

impl NotesFile {
    /// Create an empty notes file with the current notes schema version.
    pub fn empty() -> Self {
        Self {
            version: 1,
            notes: Vec::new(),
        }
    }

    /// Find a note by id. O(n); the lists never get long enough for
    /// it to matter (Phase 1 caps tool output around 30-50 notes).
    pub fn find(&self, id: &str) -> Option<&PersistedNote> {
        self.notes.iter().find(|n| n.id == id)
    }

    /// Append a fresh note. If a note with the same id already
    /// exists, replace it in-place (idempotent re-emit from the
    /// agent doesn't grow duplicates).
    pub fn upsert(&mut self, note: PersistedNote) {
        if let Some(existing) = self.notes.iter_mut().find(|n| n.id == note.id) {
            *existing = note;
        } else {
            self.notes.push(note);
        }
    }

    /// Mutate a note's status by id. No-op if the id isn't found.
    /// Returns true on hit so callers can decide whether to log a
    /// "note disappeared between emit and save" warning.
    pub fn set_status(&mut self, id: &str, new_status: &str) -> bool {
        if let Some(n) = self.notes.iter_mut().find(|n| n.id == id) {
            n.status = new_status.to_string();
            true
        } else {
            false
        }
    }
}

/// Path to `<project>/.awidat/notes.json`.
pub fn notes_file_path(project_root: &Path) -> PathBuf {
    project_root.join(".awidat").join(NOTES_FILE)
}

/// Load notes from disk. Returns empty on missing/corrupted
/// (with a `tracing::warn` on the corruption case) so the UI
/// gracefully recovers from bad state.
pub fn load_notes(project_root: &Path) -> NotesFile {
    let path = notes_file_path(project_root);
    let bytes = match std::fs::read(&path) {
        Ok(b) => b,
        Err(_) => return NotesFile::empty(),
    };
    match serde_json::from_slice::<NotesFile>(&bytes) {
        Ok(f) => f,
        Err(e) => {
            tracing::warn!(
                error = %e,
                path = %path.display(),
                "failed to parse notes.json — treating as empty",
            );
            NotesFile::empty()
        }
    }
}

/// Persist notes to disk. Creates `.awidat/` if missing.
pub fn save_notes(project_root: &Path, file: &NotesFile) -> Result<(), String> {
    let path = notes_file_path(project_root);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("create .awidat: {e}"))?;
    }
    let json = serde_json::to_vec_pretty(file).map_err(|e| format!("serialize notes: {e}"))?;
    std::fs::write(&path, json).map_err(|e| format!("write notes: {e}"))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn note(id: &str, status: &str) -> PersistedNote {
        PersistedNote {
            id: id.into(),
            kind: "silence_trim".into(),
            status: status.into(),
            anchor_at_s: 1.0,
            summary: "test".into(),
            suggested_proposal: None,
            continuity_verdict: None,
            continuity_reasons: None,
            broll_query: None,
            broll_previews: None,
            broll_anchor: None,
            author: None,
            comment_text: None,
        }
    }

    #[test]
    fn load_notes_preserves_legacy_fields() {
        let dir = tempfile::tempdir().unwrap();
        let legacy = serde_json::json!({
            "version": 1,
            "notes": [{
                "id": "n1",
                "kind": "silence_trim",
                "status": "open",
                "anchor_at_s": 1.0,
                "summary": "legacy note"
            }]
        });
        let legacy_path = notes_file_path(dir.path());
        std::fs::create_dir_all(legacy_path.parent().unwrap()).unwrap();
        std::fs::write(&legacy_path, serde_json::to_vec_pretty(&legacy).unwrap()).unwrap();

        let loaded = load_notes(dir.path());
        assert_eq!(loaded.notes.len(), 1);
        assert_eq!(loaded.notes[0].author, None);
        assert_eq!(loaded.notes[0].comment_text, None);
    }

    #[test]
    fn upsert_appends_when_id_is_new() {
        let mut f = NotesFile::empty();
        f.upsert(note("a", "open"));
        f.upsert(note("b", "open"));
        assert_eq!(f.notes.len(), 2);
    }

    #[test]
    fn upsert_replaces_when_id_matches() {
        let mut f = NotesFile::empty();
        f.upsert(note("a", "open"));
        f.upsert(note("a", "resolved"));
        assert_eq!(f.notes.len(), 1);
        assert_eq!(f.notes[0].status, "resolved");
    }

    #[test]
    fn set_status_returns_false_when_id_missing() {
        let mut f = NotesFile::empty();
        f.upsert(note("a", "open"));
        assert!(f.set_status("a", "dismissed"));
        assert!(!f.set_status("nope", "dismissed"));
    }

    #[test]
    fn load_returns_empty_when_missing() {
        let dir = tempfile::tempdir().unwrap();
        let f = load_notes(dir.path());
        assert!(f.notes.is_empty());
    }

    #[test]
    fn load_returns_empty_on_corrupted_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = notes_file_path(dir.path());
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, b"not json").unwrap();
        let f = load_notes(dir.path());
        assert!(f.notes.is_empty());
    }

    #[test]
    fn save_then_load_roundtrips() {
        let dir = tempfile::tempdir().unwrap();
        let mut f = NotesFile::empty();
        f.upsert(note("a", "open"));
        f.upsert(note("b", "dismissed"));
        save_notes(dir.path(), &f).unwrap();
        let back = load_notes(dir.path());
        assert_eq!(back.notes.len(), 2);
        assert_eq!(back.find("b").unwrap().status, "dismissed");
    }
}
